### ISSUE TITLE
Running `create_installer_windows.sh` creates disfunctional installation with additional Opam package.

### ISSUE THREAD

**Issue by trirpi** [coq/platform#105]
I've ran `coq_platform_make_windows.bat` and ran the created `Cygwin.bat` from which I installed coq-serapi succesfully!

However, after this, I wanted to create an installer using `create_installer_windows.sh`. The installer works but has an issue. The path names used are incorrect. See the exact error below.

Exact error message:

    PS C:\Coq\bin> .\sertop.exe
    (Feedback((doc_id 0)(span_id 0)(route 0)(contents(Message(level Warning)(loc())(pp(Pp_glue((Pp_string"Cannot open C:/cygwin64_coq_platform/home/trist/.opam/_coq-platform_.2021.02.1/lib/coq/theories")(Pp_print_break 1 0)(Pp_string"[cannot-open-path,filesystem]"))))(str"Cannot open C:/cygwin64_coq_platform/home/trist/.opam/_coq-platform_.2021.02.1/lib/coq/theories\n[cannot-open-path,filesystem]")))))
    (Feedback((doc_id 0)(span_id 0)(route 0)(contents(Message(level Warning)(loc())(pp(Pp_glue((Pp_string"Cannot open C:/cygwin64_coq_platform/home/trist/.opam/_coq-platform_.2021.02.1/lib/coq/user-contrib")(Pp_print_break 1 0)(Pp_string"[cannot-open-path,filesystem]"))))(str"Cannot open C:/cygwin64_coq_platform/home/trist/.opam/_coq-platform_.2021.02.1/lib/coq/user-contrib\n[cannot-open-path,filesystem]")))))
    sertop: internal error, uncaught exception:
            (CErrors.UserError
              (locate_library
                "Cannot find a physical path bound to logical path matching suffix Coq.Init."))

Notice `C:/cygwin64_coq_platform/home/trist/.opam/_coq-platform_.2021.02.1/lib/coq/theories` was the path of coq theories on the machine on which I created the installer. The newly installed platform does also contain these files but in a different location which depends on where the user opts to install.

Steps to replicate.

1. Install basic coq platfrom
2. Install coq-serapi 
3. Run `create_installer_windows.sh`
4. Use installer
5. Try to use sertop.exe created by installer

**Comment by Zimmi48** [comment]
I'm not knowledgeable enough about these scripts to debug this, but note that if you need to produce a Windows installer with a custom package set, it should also be possible for you to do that by opening a draft PR on this repo with the modified package list and leave it to GitHub Actions to generate the installer.

**Comment by trirpi** [comment]
Thanks for the suggestion! The problem is probably caused by the SerAPI package which hardcodes the Coq path upon compilation. I will try some stuff this week, and report back.

**Comment by ejgallego** [comment]
Hi @trirpi , thanks for letting me know about this issue. I am happy to help fixing this, solution should be not too hard as you already debugged it.

One question, as I stated in private I think including Coq SerAPI in the installer makes a lot of sense, should be open an issue for that first?

**Comment by Zimmi48** [comment]
@ejgallego There's already one: that's #13.
