### ISSUE TITLE
Add support for aarch64 on MacOS and Linux

### ISSUE THREAD

**Issue by djspacewhale** [coq/platform#111]
Adding support for the platform for aarch64 would be helpful - for MacOS developers it would make everything more performant on Apple silicon, and for Linux users it would allow work on a wider variety of hardware (such as Raspberry Pis or Pinebook Pros) without ssh or browser JS applets.

**Comment by MSoegtropIMC** [comment]
I am not sure this is a Coq Platform issue - if opam supports it Coq Platform will also support it.

Are you aware of any incompatibilities?

**Comment by MSoegtropIMC** [comment]
INRIA is working on getting M1 runners (see https://coq.zulipchat.com/#narrow/stream/250632-Coq-Platform-devs-.26-users/topic/Coq.20on.20Apple.20M1.20.28ARM64.29), but it will be too late for 2022.09, so I delay this to 2023.03.

**Comment by MSoegtropIMC** [comment]
On all platforms except Windows we support all platforms which opam supports. On macOS this includes aarch64. On Linux I am not sure, but I have no way to test this. Anyway if opam doesn't support it, there is nothing we can do about it. In case there is a platform which Opam supports and Coq Platform doesn't, please open a separate issue.
