### ISSUE TITLE
Add LibHyps to the platform

### ISSUE THREAD

**Issue by Zimmi48** [coq/platform#112]
LibHyps https://github.com/Matafou/LibHyps by @Matafou is a library to help manage names in Coq proofs. It's hard for this kind of small libraries to take off because they do not contain any mathematical results and users might be wary of adding them as dependency. I think that by adding the library to the platform, it would significantly help with adoption.

@Matafou this requires committing to releasing compatibility versions shortly after any new Coq version that breaks the library. If that helps, adding LibHyps to Coq's CI (so that you receive compatibility fixes whenever Coq changes) is an option.

**Comment by Matafou** [comment]
Thanks @Zimmi48 I would be happy to do the support.

**Comment by palmskog** [comment]
@Zimmi48 this is a small utility library that uses GPLv3 as license. Hence, anyone that uses it and releases their code publicly will have to make their whole project GPLv3. And as discussed on the Zulip, anyone who uses both this library and MathComp is not allowed to redistribute their compiled (e.g., `.vo`) files at all. At least in my view, having a utility library in the platform that can cause such extensive licensing problems is a bad idea.

**Comment by Matafou** [comment]
I didn’t know gpl3 was problematic should it be lgpl? What is the
recommended license then?
P

Le sam. 3 juil. 2021 à 13:19, Karl Palmskog ***@***.***> a
écrit :

**Comment by palmskog** [comment]
@Matafou LGPL would be fine by me for inclusion in the platform, since it doesn't force its users to change their licenses if they make their code public, and is not [incompatible with CECILL-B](https://www.gnu.org/licenses/license-list.html#CeCILL-B) (MathComp's license). Generally in coq-community, we [recommend](https://github.com/coq-community/manifesto#best-practices) people to use MIT or MPL-2.0. My personal preference is for the former.

**Comment by Zimmi48** [comment]
Yes, for very small libraries, MIT is the best option because it is the most permissive.

**Comment by Matafou** [comment]
I switched to MIT license. I did it by a push in the master branch on
github. I guess it is not completely regular to switch license like that
but it is really a small library.
 should I make a release now?

Pierre




Le sam. 3 juil. 2021 à 19:03, Théo Zimmermann ***@***.***> a
écrit :

**Comment by Zimmi48** [comment]
If you are the only author, it's perfectly regular like this. A new release would be good, although it can also wait a little given that the platform inclusion won't be immediate (but only in the platform version that will include 8.14 I think).

**Comment by Matafou** [comment]
OK I will wait.
P.

Le mar. 6 juil. 2021 à 15:58, Théo Zimmermann ***@***.***> a
écrit :

**Comment by Zimmi48** [comment]
@Matafou I didn't follow if there was a new version released since then, but if not, now would be a good time (ideally which would be compatible with both 8.13 and 8.14).

**Comment by MSoegtropIMC** [comment]
Looks good to me - looking at the commit history it appears that @Matafou is the only author, os the license change appears legal. I am going to include it.

**Comment by MSoegtropIMC** [comment]
Note: the license in the opam files doesn't reflect the change - this needs to be fixed and the corresponding PR should be done by @Matafou.


```
opam show coq-libhyps

<><> coq-libhyps: information on all versions <><><><><><><><><><><><><><><><><>
name         coq-libhyps
all-versions 1.0.1  1.0.2  2.0.1  2.0.2

<><> Version-specific details <><><><><><><><><><><><><><><><><><><><><><><><><>
version      2.0.2
repository   coq-released
:
:
license      "GPL-3.0-or-later"
```

**Comment by Matafou** [comment]
I will do it now. Should I modify the opam file or create a new version?

**Comment by palmskog** [comment]
@Matafou the last released version was released under the GPL, so for the new (MIT) license to apply you will have to either edit the old release or create a new release (and opam package). I recommend the latter.

**Comment by Matafou** [comment]
PR done.

**Comment by MSoegtropIMC** [comment]
Thanks! I updated libhyps to version 2.0.3.
