### ISSUE TITLE
Add coq-mathcomp-zify to the Coq Platform package

### ISSUE THREAD

**Issue by anton-trunov** [coq/platform#113]
https://github.com/math-comp/mczify -- Micromega tactics for Mathematical Components

**Comment by MSoegtropIMC** [comment]
See (https://github.com/math-comp/mczify/issues/12) for a discussion.

**Comment by MSoegtropIMC** [comment]
The maintainer agreement is here (https://github.com/math-comp/mczify/issues/12#issuecomment-927742145).

I will include it in the 2021.09 pick for 8.13 and plan to include it for the 8.14 beta.

**Comment by MSoegtropIMC** [comment]
Included with PR (https://github.com/coq/platform/pull/144)

**Comment by anton-trunov** [comment]
Thanks for the great news!
