### ISSUE TITLE
Add coq-dpdgraph to the Coq Platform

### ISSUE THREAD

**Issue by palmskog** [coq/platform#12]
[Coq-Dpdgraph](https://github.com/Karmaki/coq-dpdgraph) is a tool for building dependency graphs between Coq objects.

This is a Coq plugin which extracts out dependencies between terms. It can be used to output graphs of term relationships, and to find unused definitions and lemmas. Coq-dpdgraph has had consistent releases for new versions of Coq and is part of Coq's CI.

Since it provides useful and unique functionality to Coq project maintainers, I propose that coq-dpdgraph is included in the Coq Platform.

The maintainer of coq-dpdgraph is @ybertot.

**Comment by Karmaki** [comment]
Hi, I just have been noticed about this request by @MSoegtropIMC email. 
Since I do not use Coq myself anymore, there is very little chance that coq-dpdgraph evolves anymore, but, with the frequent help of @ybertot, I try to merge all pull request from the kind maintainers as soon as I can to keep it usable on newer Coq versions. I am happy that the Coq users find it useful, and of course agree to see it included in  the Coq Platform.
Do I have to do something on my side?

**Comment by palmskog** [comment]
@Karmaki since I believe @ybertot already handles tagging and opam packages for new Coq releases (and platform maintainers can potentially also help out with that), I don't think anything additional from your side is required (but @MSoegtropIMC can confirm).

**Comment by Zimmi48** [comment]
@Karmaki Since you are not using Coq anymore and coq-dpdgraph is already collaboratively maintained, would it make sense to transfer the repository to [coq-community](https://coq-community.org/)?

**Comment by Karmaki** [comment]
@Zimmi48 : yes, it would be a good idea. How does this? I guess there must be some kind of approval or something?

**Comment by Zimmi48** [comment]
Yes, the process is:
- open an issue on https://github.com/coq-community/manifesto, so that people are informed
- Karl or myself will add you to the coq-community members, so that you have the permissions to transfer the repo
- you proceed with the transfer
- after the transfer, we will add some standard meta-data to the repo and make you and @ybertot administrators.

**Comment by Karmaki** [comment]
OK, thanks.
Not sure to have time  to do this right now, but I'll probably (hopefully) do it next week.

**Comment by ybertot** [comment]
I have family obligations this week, but I already started preparing a new version for coq-dpdgraph.  As I understand that Karmaki agrees with it, I will also do the necessary to have the project transferred to coq-community.  It should be done by October 6th.

**Comment by Karmaki** [comment]
OK: thanks a lot to handle that @ybertot \o/

**Comment by MSoegtropIMC** [comment]
@ybertot : the 8.14 release of Coq Platform will likely happen some time in November, so there is time and no need to hurry. What I am interested in is a long term commitment. In Coq Platform we try to provide a stable foundation for Coq developments to users. Users should be able to rely on that packages are maintained.

**Comment by MSoegtropIMC** [comment]
@Zimmi48 : with "maintainer agreement" I don't mean an author agreement (which is not really needed for open source SW), but an agreement that someone is willing to maintain it according to the spirit of the Coq Platform [charter](https://github.com/coq/platform/blob/2021.02/charter.md). I would say this is still in discussion, so I added the label back.

**Comment by MSoegtropIMC** [comment]
I take the "Status" comment:

> Status: It is maintained, part of Coq-CI, with a new version produced for each release of Coq, thanks to the kind help of the main Coq developers.

in (https://github.com/coq-community/manifesto/issues/131) as maintainer agreement and will move coq-dpdgraph to the "full" level.

**Comment by MSoegtropIMC** [comment]
Sorry, I just saw that the version number is still 0.X, so by default it will go into the "extended" level.

In case you want to change this for 2021.09 please provide a justification.

The package will automatically be moved to the "full" level if the version number reaches 1.X in the future.

**Comment by Zimmi48** [comment]
@ybertot @Karmaki Since there are no plans for feature changes for this package, only baseline maintenance, wouldn't it make sense to move the version to 1.0?

**Comment by Karmaki** [comment]
Yes. Good idea. (but I cannot do it right now...)

**Comment by MSoegtropIMC** [comment]
No need to hurry - the next release is planned for November.

**Comment by MSoegtropIMC** [comment]
Of course if you are saying you will just label it 1.0 without (substantial) changes, I can include it into "full" right away. This is about the spirit, not about numbers.

**Comment by Karmaki** [comment]
Yes, since it has been stable for a while and there are no plan to make new developments, I think the only modification will be to label it 1.0. Do you agree @ybertot ?

**Comment by ybertot** [comment]
I agree that renaming the version to 1.0 is sensible, because this mirrors the stability of the basic functionality we have been maintaining over the recent years.

**Comment by ybertot** [comment]
replying to a comment of @MSoegtropIMC of 3 days ago, I will be happy to commit to maintaining this package.  Still, I would like this to be handed over to other volunteers, as soon as possible.

Yves

**Comment by MSoegtropIMC** [comment]
@ybertot : thanks for the commitment!

I moved `coq-dpdgraph` from "extended" to "full" in PR: (https://github.com/coq/platform/pull/147).
