### ISSUE TITLE
coq_platform_make_windows.bat failure trying to update cygwin

### ISSUE THREAD

**Issue by jfehrle** [coq/platform#121]
It appears that my previously installed version of cygwin is no longer available as of today, which causes the build script to fail in the `source shell_scripts/init_cygwin_fixes.sh` step.  It was working yesterday.  http://mirrors.kernel.org/sourceware/cygwin/x86_64/release/mingw64-x86_64-binutils/ shows a new version that was just pushed today, Aug 22.

As a script intended to be user-friendly, there should be a message informing the user of the failure and what to do.  And then maybe have the script continue.

```
--2021-08-22 12:19:33--  http://mirrors.kernel.org/sourceware/cygwin/x86_64/release/mingw64-x86_64-binutils/mingw64-x86_64-binutils-2.35.1-1.tar.xz
Resolving mirrors.kernel.org (mirrors.kernel.org)... 2001:4f8:4:6f:0:1994:3:14, 149.20.37.36
Connecting to mirrors.kernel.org (mirrors.kernel.org)|2001:4f8:4:6f:0:1994:3:14|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2021-08-22 12:19:33 ERROR 404: Not Found.

ERROR coq_platform_make_windows.bat failed
```

**Comment by Zimmi48** [comment]
AFAIU this was solved, wasn't it?

**Comment by jfehrle** [comment]
Yeah, I think so.
