### ISSUE TITLE
[feature request] Allow to run the test suite on package creation.

### ISSUE THREAD

**Issue by ejgallego** [coq/platform#130]
It would be convenient to have the possibility to run the test-suite when building the packages, this can be achieved with `opam -t` provided the packages support it [for Coq they should after 8.14 changes]

By the way, I find the `COQPF_` prefix better and not in conflict with other Coq variables.

This is feedback from https://github.com/coq/coq/pull/12425

**Comment by MSoegtropIMC** [comment]
Indeed, I had a similar discussion with @palmskog these days. Should be easy to implement, but I won't ask the user - just a command line option.

Actually, an `export OPAMWITHTEST=true` should do it ...

**Comment by ejgallego** [comment]
Indeed the opam variable could do it; maybe we'd like to abstract over it tho.

A bigger problem may be broken opam files, doing nothing when used with `opam install -t`; actually, i am not very familiar myself with how tests are integrated into opam.

**Comment by MSoegtropIMC** [comment]
@ejgallego : I expect that using `export OPAMWITHTEST=true` works and since we anyway didn't want to expose this to users, I think it is fine as is. If you need me to change something, please reopen.
