### ISSUE TITLE
Add Math Classes to the Coq Platform

### ISSUE THREAD

**Issue by palmskog** [coq/platform#14]
[Math Classes](https://github.com/coq-community/math-classes) is a Coq project that provides abstract interfaces for mathematical structures based on type classes.

Since Math Classes is a general, useful, and well-known library used by large projects such as [CoRN](https://github.com/coq-community/corn), I propose that it should be included in the Coq Platform. Math Classes has had consistent opam-packaged releases since Coq 8.8.

@spitters is the maintainer of Math Classes.

**Comment by MSoegtropIMC** [comment]
I already silently included it as prerequisite of CoRN (for which I took the request of @VincentSe as maintainer agreement), but I guess we should request the agreement of Bas Splitters, which I will do.

**Comment by spitters** [comment]
Yes, please add math-classes to platform.

**Comment by MSoegtropIMC** [comment]
I included `coq-math-classes.8.13.0` via (https://github.com/coq/platform/pull/143).

I plan to include it in 8.14+beta as well.
