### ISSUE TITLE
Add Paramcoq to the Coq Platform

### ISSUE THREAD

**Issue by palmskog** [coq/platform#15]
[Paramcoq](https://github.com/coq-community/paramcoq) is a Coq plugin for generating parametricity statements to perform refinement proofs.

Paramcoq provides general functionality used in several projects, such as the [CoqEAL](https://github.com/CoqEAL/CoqEAL) refinement library. It is part of Coq's CI and has had consistent opam-packaged releases since Coq 8.7. I therefore propose that it should be included in the Coq Platform.

The maintainer of Paramcoq is @proux01.

**Comment by proux01** [comment]
@MSoegtropIMC : as current maintainer of paramcoq, I do agree to the charter of the Coq platform and I'll keep releasing paramcoq for each version of Coq. The "full" level seems appropriate for paramcoq.

**Comment by MSoegtropIMC** [comment]
I included `coq-paramcoq.1.1.3+coq8.13` in the the 2021.09 pick for 8.13 in the "full" level via (https://github.com/coq/platform/pull/143).

I plan to include it in 8.14 beta as well.
