### ISSUE TITLE
Running CoqIde outside Cygwin

### ISSUE THREAD

**Issue by ThijsBeurskens** [coq/platform#151]
After following the windows installation procedure, I can't open Coqide outside the cygwin command line. If I try to open CoqIde in a normal command line, I get a couple of system errors indicating that some files were not found:

- libcairo-2.dll
- libfreetype-6.dll
- libfontconfig-1.dll
- libgdk-3.0.dll

For our use case, it is quite important that we can run coqide outside the cygwin environment. Any ideas?

**Comment by ThijsBeurskens** [comment]
Thanks for the reply!

Does the same hold for sertop and coqtop? If I try to run those I get a system/application error stating "the application was unable to start correctly (0xc000007b)". It seems as if it was possible to start sertop and coqtop outside a cygwin environment previously, since it does work on a laptop of a colleague of mine. He followed the same installation procedure, but a while ago.

For our development cycle, it is quite crucial to be able to run sertop.

**Comment by ThijsBeurskens** [comment]
Thanks a lot for your help! 

Sorry for the late reply.

We will discuss this approach on monday, but we are not sure if this solution works for us. Either way, we see that this is not an issue with the software, so if we run into further troubles we will contact you (or someone else with a more detailed description of our problem.

Thanks!

**Comment by MSoegtropIMC** [comment]
There is a dedicated Zulip channel for Coq Platform:

https://coq.zulipchat.com/#narrow/stream/250632-Coq-Platform.20devs.20.26.20users
