### ISSUE TITLE
Add Ott and its Coq library to the Coq Platform

### ISSUE THREAD

**Issue by palmskog** [coq/platform#16]
[Ott](https://github.com/ott-lang/ott) is a tool for writing definitions of programming languages and calculi that can be translated to Coq.

Ott consists of an OCaml tool (`ott`) which is packaged on the OCaml opam repository, and a Coq support library `coq-ott`. It is a generally useful tool for programming language researchers and practitioners. One project which uses Ott is the [Mi-Cho-Coq](https://gitlab.com/nomadic-labs/mi-cho-coq) project which provides a definition of the Michelson smart contract language for the Tezos blockchain.

I am the Coq maintainer for Ott and am committed to ensuring there are stable releases of `ott` and `coq-ott` to match Coq Platform releases. I therefore propose that Ott  is included in the Coq platform.

**Comment by MSoegtropIMC** [comment]
@palmskog : can you work with Peter Sewell on the inclusion agreement?

**Comment by Zimmi48** [comment]
Why do you need a statement from Peter Sewell? You said in another issue that you were looking for maintainer agreement, not author agreement, and @palmskog said:

> I am the Coq maintainer for Ott and am committed to ensuring there are stable releases of `ott` and `coq-ott` to match Coq Platform releases.

**Comment by MSoegtropIMC** [comment]
@Zimmi48 @palmskog : sorry, I missed this statement!

**Comment by MSoegtropIMC** [comment]
@palmskog : unless I am mistaken, the latest version in opam is restricted to Coq 8.11 or lower:
```
$ opam show coq-ott
:
all-versions 0.26  0.27  0.28  0.29  0.30  0.31
:
version      0.31
:
depends      "coq" {>= "8.5" & < "8.12~"}
```

**Comment by palmskog** [comment]
@MSoegtropIMC yes, if you can confirm we will add Ott and the Ott Coq library to the platform, I will make a new release that supports 8.12 to 8.14. Otherwise, a release probably won't happen for a while.

**Comment by MSoegtropIMC** [comment]
@palmskog : yes I intend to add it. For 2021.09 it might be a bit late (I try to finish it this week), but we will soon make another release (2021.11 or so).

**Comment by MSoegtropIMC** [comment]
I postponed the inclusion of Ott to the next release (planned for November). Of course if you need more time, this is also fine. In case you are super quick the door for the 2021.09 release is open until Friday, maybe Monday.

**Comment by palmskog** [comment]
@MSoegtropIMC the big barrier is not doing the release, but getting the release through the OCaml opam repository's endless CI gauntlet, which can take up to 4-5 days based on my experience. So no chance for Friday, but Monday could be a possibility.

**Comment by Zimmi48** [comment]
Well, the opam package could live in the local patch repo here until it is merged into the official opam-repository.

**Comment by MSoegtropIMC** [comment]
@palmskog : that's the reason I have the local opam patch repo - fix everything here and merge it upstream when it is finished. I would be fine to do a release with some local packages. It is trivial to use - just put the packages into the corresponding opam folders. The scripts add the corresponding folders automatically as opam repos.

But then I don't know if it makes sense to hurry this for 2 month. It is sure there will be another release soon.

**Comment by palmskog** [comment]
@MSoegtropIMC there was recently a release of Ott compatible with Coq 8.12 to 8.15: https://github.com/ott-lang/ott/releases/tag/0.32

However, it hasn't been submitted as a package to OCaml opam archive yet. After that is up, it would take me a minute to add the coq-ott package to the Coq opam archive. I guess I can do the OCaml opam archive PR if there's a chance to add Ott for the 2022.03 Platform.

**Comment by MSoegtropIMC** [comment]
@palmskog : if the opam package is there until say Wednesday, things should be fine for 2022.03.

Please note that Coq Platform has patch repos for both, the OCaml repo and the Coq repo and if the only issue is to get the opam package in, I wouldn't have an issue to release a Coq Platform with this in the local repos.

**Comment by MSoegtropIMC** [comment]
@palmskog : can you give me an update on this? As I said, I would be fine with including both opam packages (the OCaml and the Coq one) in the local patch repo for the release. I would need either this (a PR towards Coq Platform's opam repos) or the published packages by tomorrow evening for 2022.03.

**Comment by MSoegtropIMC** [comment]
@palmskog : yes, please. I can't promise that I can finish everything and release this week, but I don't want to start testing new packages the last minute. If the packages make it to the public repos before I release, I would remove them again. In the end I have the local repos for exactly such cases.

**Comment by MSoegtropIMC** [comment]
@palmskog : I wanted to ask what the status of the opam packages (either in the local or official repos) is. I can delay the release a few days, say until Tuesday next week (that is packages are there on Monday) if you say a few days would help.

**Comment by MSoegtropIMC** [comment]
@palmskog : one last thing: can you recommend a few (at most 3) smoke test files? They should coqc all together in < 10s on a current machine and essentially test if coq-ott has been installed. I currently don't have smoke tests for tools like ott itself, but plan for this in the near future, so some commands I could run would also be helpful.

**Comment by palmskog** [comment]
Ott is mostly in maintenance mode. The only changes I plan to do are to add optional features for Coq, such as specifying the universe of a relation (lift the restriction of `Prop`-only relations).

Would be nice to see it in full, but I don't think I can persuade the Cambridge side to suddenly switch to version 1.0. So extended is also fine.

**Comment by MSoegtropIMC** [comment]
We have a few 0.X packages in full. Sometimes it is just a historic artifact. It is about content, not numbers. So I think it is appropriate to add it to full.

**Comment by MSoegtropIMC** [comment]
I mean that packages have 0.X numbers is an historic artifact.

**Comment by MSoegtropIMC** [comment]
Yes, this is what I meant - people just never made the decision to name it 1.0.

I can imagine some nice applications of Ott in my world btw. - I will definitely see what it can do.

**Comment by MSoegtropIMC** [comment]
@palmskog : the ott package does not compile on Windows (coq-ott does). I right now have no time to look into why. Do you think coq-ott is useful without ott - one probably can still work with Coq files produced with ott on another machine. One issue would be running the smoke test without ott.

**Comment by palmskog** [comment]
@MSoegtropIMC the story is similar to `coq-hammer` and `coq-hammer-tactics`:
- `coq-ott` corresponds to `coq-hammer-tactics` in that a file generated by Ott only needs this library to work, so people can check the generated files into version control and depend only on this package.
- `ott` corresponds to `coq-hammer` in that there is something in the package that *generates* Coq code.

If you want a smoke test for only `coq-ott`, here is the [regexp.v](https://gist.githubusercontent.com/palmskog/d61515d53d04b3804d11e262e921a7ba/raw/12fe47c5999ec5007ef98fc966d2d0c6c691a362/regexp.v) file I get locally, which should be the same file generated by any compiled `ott` executable compiled from 0.32 source.

**Comment by MSoegtropIMC** [comment]
@palmskog : yes, this is what I thought as well, so I enabled coq-ott on Windows. Maybe I can even fix Ott on Windows, so I left the smoke test empty for the time being. Would the above link be available permanently? For license reasons I can't include it in the Coq Platform repo.

Ott is included by #233.

**Comment by palmskog** [comment]
@MSoegtropIMC what license do you want the files under? The Ott file (regexp.ott) was written by me, and the regexp.v file was generated by me, so I own the copyright to both and can license them under some suitable license. While the gists will probably be available for the foreseeable future, it's better to have the files in the actual smoke test kit, in my view.

**Comment by MSoegtropIMC** [comment]
Coq Platform is CC-0 (because the main opam repo is CC-0), so if you could contribute the file under CC-0 this would help.

I suggest you create a new folder under root called `smoke_test_files/coq-ott` or maybe `test_files/coq-ott` and put the file in there.

**Comment by MSoegtropIMC** [comment]
@palmskog : to make it work on windows I need this:
```
build: [
  [make "world"]
  ["rm" "src/ott"]
  ["cp" "src/ott.opt" "src/ott"]
  [make "ott.install"]
]
```
The reason is that for installation via `.install` files opam uses a MinGW executable, which does not understand cygwin symlinks. Since src/ott is a symlink to src/ott.opt, the copy of src/ott to prefix/bin fails. I guess you can find a more elegant solution.

**Comment by MSoegtropIMC** [comment]
@palmskog : another thing: on Windows it is quite bad to have files named "aux" because this is a reserved filename independent of path and e.g. quite hard to delete.
