### ISSUE TITLE
Support for Apple Silicon?

### ISSUE THREAD

**Issue by k4rtik** [coq/platform#168]
Hi

When I tried the 2021.09.0 install script for macOS on an M1 Macbook Air, I received the error that `uname -m` output of "arm64" was unrecognized.

Are Apple's new SoCs supported at all?

**Comment by MSoegtropIMC** [comment]
Sorry - not yet, mostly because we have no means to do CI tests.

But as far as I know opam does support it, so it shouldn't be that hard to fix. I would appreciate if you could try it.

**Comment by MSoegtropIMC** [comment]
For this specific error, the fix should be to add to the case in `shell_scripts/init_machine_type.sh` these lines:

```
    arm64)
      BITSIZE=64
      HYPHEN32=
      HYPHEN64=-64
      ;;
```

You might encounter a few other places ...

**Comment by k4rtik** [comment]
Ah, that's good to know. I was surprised that the lack of support was not documented anywhere in the repo.

When I get a chance to test, I will report back here.

**Comment by Zimmi48** [comment]
We should probably add a link to this known issue from the release notes.

**Comment by MSoegtropIMC** [comment]
@Zimmi48 : yes done. I also encouraged people who have Apple silicon to ping us for a remote debug session.

**Comment by k4rtik** [comment]
Alright, with the changes that @MSoegtropIMC suggested above I got up to the following:

```
===== CHECKING VERSION OF INSTALLED OPAM =====
Found opam 2.1.0 - good!
/opt/homebrew/bin/opam
===== opam already initialized =====
===== CREATE OPAM SWITCH =====
[__coq-platform.2021.09.0.patch_ocaml] Initialised
[__coq-platform.2021.09.0.patch_coq-released] Initialised
[__coq-platform.2021.09.0.patch_coq-dev] Initialised
[coq-released] Initialised
[coq-core-dev] Initialised
[coq-extra-dev] Initialised

<><> Installing new switch packages <><><><><><><><><><><><><><><><><><><><>  🐫
Switch invariant: ["ocaml-base-compiler" {= "4.10.0"}]
[ERROR] Could not determine which packages to install for this switch:
  * Missing dependency:
    - ocaml-base-compiler = 4.10.0
    unmet availability conditions: '!(os = "macos" & arch = "arm64")'


Switch initialisation failed: clean up? ('n' will leave the switch partially installed) [Y/n] y
```

But after changing the ocaml-base-compiler version to [4.10.2 that supports arm64](https://ocaml.org/releases/4.10.2.html) at: https://github.com/coq/platform/blob/2bcf19aa885cb64b3d21c74126ad83ccb5e89577/shell_scripts/install_opam.sh#L170
I was able to proceed seamlessly. Here's a log for specifics: https://gist.github.com/k4rtik/e23a87f573c7b6e16cac4ec1c89615cc

**Comment by k4rtik** [comment]
Unsure if the maintainers want to wait until the availability of the CI to add (unofficial) support to the scripts. If it's not a blocker, I am happy to submit a PR.

PS: I may be able to test with other versions of Coq supported in version 2021.09.0, at least for the base installs.

**Comment by MSoegtropIMC** [comment]
@k4rtik : I would be fine to have a "not official / beta" support for Apple silicon.

Regarding ocaml: it might suffice to change the OCaml version to 4.10.2.

See [4.10.0](https://github.com/ocaml/opam-repository/blob/5f7b62a5f262f2dc7f3f51991e2da930cd0d4f56/packages/ocaml-base-compiler/ocaml-base-compiler.4.10.0/opam#L44) vs [4.10.2](https://github.com/ocaml/opam-repository/blob/5f7b62a5f262f2dc7f3f51991e2da930cd0d4f56/packages/ocaml-base-compiler/ocaml-base-compiler.4.10.2/opam#L43).

One would have to change this here (keep the cygwin version as is):

https://github.com/coq/platform/blob/2bcf19aa885cb64b3d21c74126ad83ccb5e89577/shell_scripts/install_opam.sh#L170

**Comment by MSoegtropIMC** [comment]
P.S.: The ocaml version chosen is the same for all versions of Coq in Coq Platform 2021.09.0.

**Comment by MSoegtropIMC** [comment]
@k4rtik : sorry, I didn't see the second part of your post - so with the two changes it does work on Apple silicon?

Can you please try "extended/x" instead of "base/b"?

If this works, I would appreciate a PR. The only thing we have to check is if 4.10.2 is available on Windows, but I wouldn't see it as a blocker to have 4.10.0 on Windows and 4.10.2 elsewhere. Also I would ask you to check new versions of the Coq Platform in a timely manner (until I can get my own M1 Mac mini back to life - I bricked it in an attempt to install a fresh OS for testing ...).

**Comment by k4rtik** [comment]
> @k4rtik : sorry, I didn't see the second part of your post - so with the two changes it does work on Apple silicon?

No problem and yes, it worked without any issue with base.

> Can you please try "extended/x" instead of "base/b"?

I will try later this week.

> If this works, I would appreciate a PR. The only thing we have to check is if 4.10.2 is available on Windows, but I wouldn't see it as a blocker to have 4.10.0 on Windows and 4.10.2 elsewhere. 

The page I linked to for 4.10.2 above does confirm support for Windows/Cygwin:
```
Source distribution
Source tarball (.tar.gz) for compilation under Unix (including Linux and macOS)
and Microsoft Windows (including Cygwin).
```

> Also I would ask you to check new versions of the Coq Platform in a timely manner (until I can get my own M1 Mac mini back to life - I bricked it in an attempt to install a fresh OS for testing ...).

I can't promise this yet as I am yet to receive my own M1 Pro machine. I have been trying out M1 on a friend's machine released last year to make sure that the things I need will work. But happy to help when I can.

**Comment by k4rtik** [comment]
I am trying the extended install. The first error I ran into is package `gappa` is unable to find `gmp` which is actually installed:

```
[ERROR] The compilation of gappa.1.4.0 failed at "./configure CXXFLAGS=-I/opt/local/include --prefix=/Users/kartik/.opam/__coq-platform.2021.09.0~8.13".
```

Full log for `opam install gappa`:
```
kartik@Kartiks-MacBook-Pro platform % opam install gappa
The following actions will be performed:
  ∗ install gappa 1.4.0

<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><>  🐫
⬇ retrieved gappa.1.4.0  (cached)
[ERROR] The compilation of gappa.1.4.0 failed at "./configure CXXFLAGS=-I/opt/local/include --prefix=/Users/kartik/.opam/__coq-platform.2021.09.0~8.13".

#=== ERROR while compiling gappa.1.4.0 ========================================#
# context     2.1.1 | macos/arm64 | ocaml-base-compiler.4.10.2 | https://opam.ocaml.org#38d03f63
# path        ~/.opam/__coq-platform.2021.09.0~8.13/.opam-switch/build/gappa.1.4.0
# command     ~/.opam/opam-init/hooks/sandbox.sh build ./configure CXXFLAGS=-I/opt/local/include --prefix=/Users/kartik/.opam/__coq-platform.2021.09.0~8.13
# exit-code   1
# env-file    ~/.opam/log/gappa-47045-90ddec.env
# output-file ~/.opam/log/gappa-47045-90ddec.out
### output ###
# [...]
# checking whether gcc accepts -g... yes
# checking for gcc option to enable C11 features... (cached) none needed
# checking how to run the C preprocessor... gcc -E
# checking how to run the C++ preprocessor... g++ -E
# checking for g++... g++
# checking whether the compiler supports GNU C++... (cached) yes
# checking whether g++ accepts -g... yes
# checking for g++ option to enable C++11 features... (cached) none needed
# checking how to run the C++ preprocessor... g++ -E
# checking whether g++ supports C++11 features with -std=gnu++11... yes
# checking for __gmpz_init in -lgmp... no
# configure: error:  *** Unable to find GMP library (http://www.swox.com/gmp/)



<><> Error report <><><><><><><><><><><><><><><><><><><><><><><><><><><><><>  🐫
┌─ The following actions failed
│ λ build gappa 1.4.0
└─
╶─ No changes have been performed
# Run eval $(opam env) to update the current shell environment
kartik@Kartiks-MacBook-Pro platform %
```

I believe the source of this error might be 

https://github.com/coq/platform/blob/2bcf19aa885cb64b3d21c74126ad83ccb5e89577/opam/opam-coq-archive/extra-dev/packages/gappa/gappa.dev/opam#L16

because on arm64 homebrew installed gmp is found at `/opt/homebrew/include`

**Comment by k4rtik** [comment]
Found the issue, the `configure` commands needs to be passed the following: `CPPFLAGS=-I/opt/homebrew/include LDFLAGS=-L/opt/homebrew/lib` to find gmp and boost libraries for `gappa`.

**Comment by k4rtik** [comment]
Just adding some stats here as I try some combinations of packages on main branch after merge of #171:

|  Desc |  Time |
|---|---|
| x,1,p,4,y,y  |  31m40s |
|   |   |
|   |   |
|   |   |
|   |   |

**Comment by k4rtik** [comment]
I was able to compile the failing config in the table above, so I am happy to consider this issue resolved.

Let me know if you need me to test any other specific config. I should have easy access to a M1 Pro machine for the foreseeable future.

**Comment by MSoegtropIMC** [comment]
Thanks for your help with this!

It would make sense to test the 8.14+beta2 config as well.

Please note that the config numbers will change soon in main.

I keep the issue open until release so that people more easily find it.

**Comment by k4rtik** [comment]
> It would make sense to test the 8.14+beta2 config as well.

Do you test it with some option other than full (f)? I did test it for full and base as shown in the table above.

**Comment by k4rtik** [comment]
So I just tried installing `__coq-platform.2021.11.0~8.14~2021.11` with f,1,p,4,y,y options and it took my machine 29m 20s. With the same options, it took 27m 25s for `__coq-platform.2021.11.0~8.13~2021.11`.

I think I am quite satisfied. Let me know if you need me to test any other config.

**Comment by MSoegtropIMC** [comment]
Thanks for the tests - indeed this is quite fast. Just to make sure: this where builds from scratch - not just an update of an already existing switch?

I am about to add a few more non Coq ocaml packages, notably a generator for prime proofs (currently in CI) and a special Z3 for Coq hammer. These might be tricky on ARM silicon. I will ping you as soon as it passed the other CI.

**Comment by MSoegtropIMC** [comment]
P.S.: in general it would make sense to test the 'x' variant - it should take only slightly longer.

**Comment by k4rtik** [comment]
Oh I was under the impression that full had more packages than extended.

**Comment by k4rtik** [comment]
> Just to make sure: this where builds from scratch - not just an update of an already existing switch?

Yes. Sometimes these include times for downloading packages, but that will only be an overestimate then, not underestimate.

**Comment by k4rtik** [comment]
> a special Z3 for Coq hammer. These might be tricky on ARM silicon.

Hope it's not too special, we had a fun time getting [a new Z3 version out](https://github.com/ocaml/opam-repository/pull/20065) that works on macOS. But it helps that I got to participate in that process.

**Comment by MSoegtropIMC** [comment]
As far as my limited understanding goes, this is just a different frontend which uses the usual Z3 shared library.

**Comment by k4rtik** [comment]
I see. The main change we may have to do on macOS is to use the dynamic library instead. But happy to investigate when it's ready.

**Comment by MSoegtropIMC** [comment]
@k4rtik : in https://github.com/coq/platform/issues/186 it was reported that OCaml 4.10.2 doesn't work for WSL2 (Windows Subsystem for Linux). The reporter found that 4.13.1 does work. Would you ming to test if 4.13.1 also works for Apple Silicon?

**Comment by MSoegtropIMC** [comment]
P.S.: better test 4.13.2 - the latest patch release for 4.13.

**Comment by k4rtik** [comment]
Just to be sure, I don't see an `ocaml-base-compiler` release for 4.13.2 yet, just up to 4.13.1: https://opam.ocaml.org/packages/ocaml-base-compiler/

4.13.1 currently fails as follows:
```
===== UPDATE OPAM REPOSITORIES =====

<><> Updating package repositories ><><><><><><><><><><><><><><><><><><><><>  🐫
[__coq-platform.2021.11.0.patch_ocaml] no changes from file:///Users/kartik/Hub/platform/opam/opam-repository
[__coq-platform.2021.11.0.patch_coq-released] no changes from file:///Users/kartik/Hub/platform/opam/opam-coq-archive/released
[coq-released] no changes from https://coq.inria.fr/opam/released
[default] no changes from https://opam.ocaml.org
POL="$POL"'(allow network* (remote unix))'
===== INSTALL PREREQUISITES =====
[ERROR] Package conflict!
  * Missing dependency:
    - ppxlib = 0.15.0 → ocaml-migrate-parsetree < 2.0.0 → ocaml-variants = 4.08.0+beta2
    unmet availability conditions: '!(os = "macos" & arch = "arm64")'
  * Missing dependency:
    - ppxlib = 0.15.0 → ocaml-migrate-parsetree < 2.0.0 → ocaml-variants = 4.08.0+beta3
    unmet availability conditions: '!(os = "macos" & arch = "arm64")'

[WARNING] set was deprecated in version 2.1 of the opam CLI. Use opam var instead or set OPAMCLI environment variable to 2.0.
Added 'jobs: "4"' to field variables in switch __coq-platform.2021.11.0~8.14~2021.11
===== INSTALL OPAM PACKAGES (PARALLEL) =====
[ERROR] Package conflict!
  * Missing dependency:
    - ppxlib = 0.15.0 → ocaml-migrate-parsetree < 2.0.0 → ocaml-variants = 4.08.0+beta2
    unmet availability conditions: '!(os = "macos" & arch = "arm64")'
  * Missing dependency:
    - ppxlib = 0.15.0 → ocaml-migrate-parsetree < 2.0.0 → ocaml-variants = 4.08.0+beta3
    unmet availability conditions: '!(os = "macos" & arch = "arm64")'

No solution found, exiting
```

**Comment by k4rtik** [comment]
@MSoegtropIMC it seems this dependency problem is not specific to Apple Silicon, it may appear on all platforms. I see:
```
PACKAGES="${PACKAGES} PIN.ppxlib.0.15.0"            # coq-serapi requires this old version
```
in several package picks.

**Comment by MSoegtropIMC** [comment]
@k4rtik : thanks for testing! The 4.13.1 vs 4.13.2 is different if looks at the "ocaml" metapackage and the "ocaml-base-compiler" package. ocaml does have 4.13.2 but ocam-base-compiler doesn't. I can't say how relevant this is.

The ppxlib down version is required by serapi - it can't live yet with a newer version.

So in case of doubt I would drop serapi and keep elpi. If serapi is dropped, the restriction to ppxlib.0.15.0 can be dropped.

@ejgallego : FYI.

**Comment by k4rtik** [comment]
> ocaml does have 4.13.2 but ocam-base-compiler doesn't. I can't say how relevant this is.

It might be a convenience package for testing before release as the latest on [ocaml.org](https://ocaml.org/) is also still 4.13.1 In any case, it's not installable using opam switch create:

```
$ opam switch create 4.13.2
[ERROR] No compiler matching `4.13.2' found, use `opam switch list-available' to see what is available, or use `--packages'
        to select packages explicitly.
```

**Comment by Blaisorblade** [comment]
Tried basic pick, time for the extended one next: `time ./coq_platform_make.sh -extent=x -pick=8.13~2021.11 -parallel=p -jobs=16 -compcert=y -vst=y -switch=d`
```
time ./coq_platform_make.sh -extent=b -pick=8.13~2021.11 -parallel=p -jobs=16

real	3m37.415s
user	9m59.257s
sys	2m18.464s
$ system_profiler SPHardwareDataType
Hardware:

    Hardware Overview:

      Model Name: MacBook Pro
      Model Identifier: MacBookPro18,2
      Chip: Apple M1 Max
      Total Number of Cores: 10 (8 performance and 2 efficiency)
      Memory: 64 GB
      [snipped for privacy]
```

**Comment by MSoegtropIMC** [comment]
@Blaisorblade : how much RAM to do you have?

**Comment by Blaisorblade** [comment]
@MSoegtropIMC 64 GB

**Comment by k4rtik** [comment]
And here's the output from my final machine (note higher CPU count and same RAM):
```
❯ system_profiler SPHardwareDataType
Hardware:

    Hardware Overview:

      Model Name: MacBook Pro
      Model Identifier: MacBookPro18,3
      Chip: Apple M1 Pro
      Total Number of Cores: 10 (8 performance and 2 efficiency)
      Memory: 32 GB
[...]
❯ git describe
2021.09.0-54-g8568054
❯ time ./coq_platform_make.sh -extent=x -pick=8.14~2021.11 -parallel=p -jobs=16 -compcert=y -vst=y -switch=d
[...]
real	25:42.57
user	2:16:23.56
sys	13:23.00
❯ time ./coq_platform_make.sh -extent=x -pick=8.13~2021.11 -parallel=p -jobs=16 -compcert=y -vst=y -switch=d
[...]
real	25:36.52
user	2:21:38.58
sys	12:46.15
❯ time ./coq_platform_make.sh -extent=x -pick=8.12 -parallel=p -jobs=16 -compcert=y -vst=y -switch=d
[...]
real	19:21.28
user	1:12:11.36
sys	6:42.23
```
Clear improvement of 3 to 5 minutes with two extra cores.

**Comment by Blaisorblade** [comment]
Cool! Haven't tried 8.12 but the other times seem to match my M1 Max 64 GB, which will help people save quite a bit.

**Comment by k4rtik** [comment]
Right, I feel like it means 32GB will be sufficient for most people's needs (while 16GB was too constraining).

**Comment by k4rtik** [comment]
Hi @MSoegtropIMC I tried installing `__coq-platform.2022.01.0~8.14~2022.01` and `__coq-platform.2022.01.0~8.15~preview1` last night with your commit 7cf8bc1 (prep3) and had no issues.

Do you think we can close this issue now?

**Comment by MSoegtropIMC** [comment]
Thanks for your continued test efforts!

I don't think the other configurations make any difference in arm vs intel code, so I will close this issue.

**Comment by Zimmi48** [comment]
There is now a GitHub roadmap item (with no ETA) about M1 support: https://github.com/github/roadmap/issues/528

**Comment by MSoegtropIMC** [comment]
I don't expect this to be realized any time soon - afaik there is no M1 HW which is suitable for large data centers. A web search shows that those who offer M1 servers base this on Mac Mini. For small applications (like a Coq CI) a bunch of MacMinis in a rack is fine, but  I can't quite imagine that Github will do this.
