### ISSUE TITLE
Canonical naming of variants of Platform releases

### ISSUE THREAD

**Issue by palmskog** [coq/platform#179]
In the [release notes for 2021.09](https://github.com/coq/platform/releases/tag/2021.09.0), there is no clear terminology to distinguish different *variants* of the Platform release, that is, the different collections with Coq and packages that comprise the release. This means that one can no longer unambiguously claim that a certain Coq project repo commit or tag is *Coq Platform 20XX.YY compatible", since the project may work with one combination of Coq version and package collection but not another in the same Platform release.

For example, I might have a project compatible with Coq 8.13.2 and the 2021.02 collection of packages that is *not* compatible with 8.13.2 and the 2021.09 collection. To make matters worse, my project might not even be compatible with the Coq Platform 2021.02 release, since it relies on some bugfix to the 2021.02 packages that only appeared in the 2021.09 release.

To enable making verifiable compatibility claims, I think there should be some official terminology to pinpoint a specific opam switch generated by a Coq Platform release. This would also be needed for testing compatibility using, say, a Docker image.

For example, we could say explicitly that a Platform release consists of several **variants**:
- `2021.09.0+8.13+recommended` (for 8.13.2 with *latest* package collection)
- `2021.09.0+8.13+compatibility` (for 8.13.2 with *old* package collection)
- `2021.09.0+8.14+experimental` (for 8.14.0 with beta package collection)

**Comment by MSoegtropIMC** [comment]
I reworked the use of terms like "version", "variant", "release" and so on in main.

- Coq **version**
- Coq Platform **release**
- Package **pick**

The latter one could also name **variant**, but I think package pick is clearer.

I will do another PR to add the suggested labels **latest-stable** and **beta**, but it gets tight in the one liner descriptions of the the package picks.

**Comment by palmskog** [comment]
This solves the issue as far as I am concerned, but I repost here for reference the tentative identifiers of each opam switch that were discussed on Zulip (`<platform-release>-<coq-version>-<package-pick>`):

Current release:
- `2021.09.0-8.13-2021.09` / `latest-stable`
- `2021.09.0-8.13-2021.02`
- `2021.09.0-8.14-2021.09` / `latest-beta`

Then once release 2021.11.0 is out we get:
- `2021.11.0-8.14-2021.11` / `latest-stable`
- `2021.11.0-8.13-2021.09`
- `2021.11.0-8.13-2021.02`

**Comment by MSoegtropIMC** [comment]
Please note that in main the opam switches are named as above (with a __coq_platform prefix), but the separator is not - but ~, so it is e.g. `2021.11.0~8.14~2021.11`. Is far as I remember this has some advantages in compatibility with various version ordering mechanisms in use, but I can't say I remember the exact details.

**Comment by Zimmi48** [comment]
I think ~ vs - only matters for actual version names, not for names of switches (which are not ordered).

**Comment by palmskog** [comment]
Yes, `~` should not matter for switch names. Hence, to make Érik's life easier when generating Docker images, we may want to consider renaming the switches using only `-`, according to format `__coq_platform_<platform-release>-<coq-version>-<package-pick>`, for example:
- `__coq_platform-2021.09.0-8.13-2021.09`
- ``__coq_platform-2021.09.0-8.13-2021.02`
- ``__coq_platform-2021.09.0-8.14-2021.09`

**Comment by MSoegtropIMC** [comment]
Originally it was like that and afair someone convinced me to use ~ instead of -, but I can change it back.
