### ISSUE TITLE
Add Regular Language Representations to the Coq Platform

### ISSUE THREAD

**Issue by palmskog** [coq/platform#18]
[Regular Language Representations in Coq](https://github.com/coq-community/reglang) (RegLang) is a Coq library with definitions and verified translations between different representations of regular languages: various forms of automata, regular expressions, and the logic WS1S. It uses the `ssreflect` library from MathComp.

Finite automata and regexps are standard CS concepts that are currently not found in the Coq Stdlib. RegLang provides general and flexible representations of these and related concepts designed for convenient reasoning using the SSReflect proof language. The library is maintained in coq-community and has had stable releases for Coq since 8.8. I therefore propose that it should be included in the Coq Platform.

I am one of the maintainers of RegLang, but as the main author and maintainer, @chdoc should have ultimate veto over inclusion into the platform.

**Comment by chdoc** [comment]
I am certainly not going to veto the inclusion of RegLang in the Coq platform.

**Comment by palmskog** [comment]
There is now a [release](https://github.com/coq-community/reglang/releases/tag/v1.1.1) of RegLang compatible with packages already in the platform. This RegLang release is suitable for inclusion in the 8.12 platform. The corresponding [opam package](https://github.com/coq/opam-coq-archive/blob/master/released/packages/coq-reglang/coq-reglang.1.1.1/opam) has been merged to the Coq opam archive.

**Comment by MSoegtropIMC** [comment]
@palmskog : can you please recommend an example file for the smoke test kit?

I randomly selected `theories/regexp.v`, but its compile time is a bit longer than average (not excessive, though).

**Comment by palmskog** [comment]
@MSoegtropIMC I would recommend the file `theories/dfa.v` as smoke test, which is file closest to the root in the file dependency graph that is actually about regular languages. It takes around a second to check on my machine.

**Comment by palmskog** [comment]
For the platform release for 8.14, I would recommend using the 1.1.2 release of reglang ([opam package](https://github.com/palmskog/opam-coq-archive/blob/4ce0df3d0cde74ddfd377cd3170832a2b072ad0d/released/packages/coq-reglang/coq-reglang.1.1.2/opam)), **if** the platform will include MathComp 1.12.0, which the package depends on via `ssreflect`.

If the MathComp maintainers will do a new release for Coq 8.14, then I think we would need to do a new release of reglang.

**Comment by MSoegtropIMC** [comment]
@chdoc, @palmskog : thanks, I updated the smoke test kit and I included coq-reglang.1.1.2 in the 2021.09 pick for 8.13 via (https://github.com/coq/platform/pull/143).

I plan to include the same version in 8.14 beta.
