### ISSUE TITLE
CoqIDE on recent macOS from Coq Platform installed via the DMG file cannot access the Documents directory

### ISSUE THREAD

**Issue by lukaszcz** [coq/platform#188]
When Coq Platform for macOS is installed via the DMG package, CoqIDE by default does not have permission to access the Documents directory. This is confusing and tedious to fix by the user, as no pop-up window is directly displayed to grant access -- the user needs to search through macOS options by themselves.

This probably affects all recent macOS versions which require granting separate permission for access to the Documents directory.

I used: Coq_Platform_2021.09.0.8.14+beta2-installer-macos-signed.dmg

**Comment by adah1972** [comment]
Same problem with Coq 8.13.2 on macOS Catalina.

**Comment by rohit-chadha** [comment]
I also have the same issue. Does anyone have a workaround?

**Comment by makarius** [comment]
This is a standard problem for macOS "app" bundles with a shell script as executable. See the following solution for Isabelle: https://isabelle-dev.sketis.net/T37

**Comment by MSoegtropIMC** [comment]
@makarius : thanks for the pointer! If I understand this right the solution is to write a short console executable which replaces the shell script (or calls it).

Should be doable for the next release. Until then the only solution is to put your Coq files somewhere else.
