### ISSUE TITLE
UniMath build fails with 3 make jobs and 8GB RAM on WSL2 Ubuntu

### ISSUE THREAD

**Issue by djspacewhale** [coq/platform#190]
I recognize that this build issue is perhaps better suited to the UniMath team directly, but I think it's worth acknowledging here to update the current recommended packages. On less-powerful machines (my work laptop with 8GB RAM), building UniMath with fewer sequential make jobs results in the build job failing. Full error text follows:
```
The following actions will be performed:
  ∗ install coq-unimath 20210807

<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><><><>
⬇ retrieved coq-unimath.20210807  (https://github.com/UniMath/UniMath/archive/refs/tags/v20210807.tar.gz)
[ERROR] The compilation of coq-unimath.20210807 failed at "make BUILD_COQ=no -j3".

#=== ERROR while compiling coq-unimath.20210807 ===============================#
# context              2.1.0 | linux/x86_64 | ocaml-base-compiler.4.10.0 | https://coq.inria.fr/opam/released#2021-12-29 12:40
# path                 ~/.opam/__coq-platform.2021.09.0~8.13/.opam-switch/build/coq-unimath.20210807
# command              ~/.opam/opam-init/hooks/sandbox.sh build make BUILD_COQ=no -j3
# exit-code            2
# env-file             ~/.opam/log/coq-unimath-1604-a0fa30.env
# output-file          ~/.opam/log/coq-unimath-1604-a0fa30.out
### output ###
# [...]
# scope cat. [notation-incompatible-format,parsing]
# File "./UniMath/CategoryTheory/All.v", line 205, characters 0-70:
# Warning: Notation "_ ^op" was already defined with a different format in
# scope cat. [notation-incompatible-format,parsing]
# COQC UniMath/Bicategories/DisplayedBicats/FiberBicategory/FiberBicategory2.v
# COQC UniMath/Bicategories/Transformations/Examples/Whiskering.v
# Killed
# make[2]: *** [build/CoqMakefile.make:720: UniMath/Bicategories/DisplayedBicats/Examples/DisplayedInserter.vo] Error 137
# make[2]: *** Waiting for unfinished jobs....
# make[1]: *** [build/CoqMakefile.make:343: all] Error 2
# make[1]: Leaving directory '/home/dj/.opam/__coq-platform.2021.09.0~8.13/.opam-switch/build/coq-unimath.20210807'
# make: *** [Makefile:92: all] Error 2



<><> Error report <><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
┌─ The following actions failed
│ λ build coq-unimath 20210807
└─
```

**Comment by MSoegtropIMC** [comment]
Yes, I thought about making Unimath optional and/or introducing a separate level for things which are well maintained but big.

One question: how is memory handled with WSL2? You say your Laptop has 8GB - how much memory does WSL2 have then? I expect that this is much less than 8 GB - maybe 4 GB. I actually did test this with 8GB RAM on a Ubuntu VM (I mean 8GB assigned to the VM, not 8 GB host memory).

**Comment by djspacewhale** [comment]
I just ran htop inside my Ubuntu system and it shows 3.69GB of available RAM, with 1GB swap. So I guess that with 2 sequential make jobs isn't enough to compile UniMath.

**Comment by MSoegtropIMC** [comment]
@djspacewhale : As far as I can tell it behaves as the documentation says. If you use WSL you can obviously count the memory available to WSL only, which is 4 GB. In this situation the documentation recommends 2 make jobs, but you used 3:

`"make BUILD_COQ=no -j3"`

Does it work with 2?

Do you think it is required to hint users that when using virtualization, that they need to take the memory of their VM into account - not the complete available memory.

**Comment by MSoegtropIMC** [comment]
Since there is no feedback and this seems to behave as documented, I am closing this issue.
