### ISSUE TITLE
installation failed

### ISSUE THREAD

**Issue by dnaumann** [coq/platform#20]
The setup script failed for me.  Using macOS and macports.  Edited the script to use full version since I need clightgen
(opam install coq-compcert.3.7+8.12~coq_platform).
In brief it's opam packages:
┌─ The following actions failed
│ λ build coq-coquelicot 3.1.0
│ λ build coq-flocq      3.3.1

Here's the full trace FWIW.
[coq-platform-error-trace.txt](https://github.com/MSoegtropIMC/coq-platform/files/5042334/coq-platform-error-trace.txt)

**Comment by dnaumann** [comment]
As a workaround I disabled sandboxing (by editing ~/.opam/config to remove the lines having to do with wrap-*-commands) and then the installation script ran to successful completion.  For coq-flocq the workaround is noted here:
https://github.com/vellvm/vellvm#notes

**Comment by MSoegtropIMC** [comment]
I believe this has been fixed a while ago by the macOS sandbox sanity check script `https://github.com/coq/platform/blob/2021.02/shell_scripts/check_opam_sandbox.sh` (I had some private communication with @dnaumann on this). @dnaumann : in case the issue is still there, please reopen.
