### ISSUE TITLE
Align messages and behavior re Coq switches

### ISSUE THREAD

**Issue by Blaisorblade** [coq/platform#210]
Suggestions are given in https://github.com/coq/platform/pull/209#issuecomment-1027815516 and https://github.com/coq/platform/pull/209#issuecomment-1027836250.

**Comment by Blaisorblade** [comment]
Thanks a lot!

**Comment by MSoegtropIMC** [comment]
I say thank you! I took btw. most of your PR - it just needed a few fixes (there was another place where I called opam switch).
