### ISSUE TITLE
CoqIDE "Cannot open pixbuf loader module file" console message at startup

### ISSUE THREAD

**Issue by jfehrle** [coq/platform#212]
Running (e.g. by double-clicking in File Manager) CoqIDE installed with the CI-built Windows installer generates the following messages in a new command window before opening the CoqIDE window.  The suggested remedy doesn't work.  The command window remains open; closing the command window kills CoqIDE.  Icons appear normal in CoqIDE.

8.13 doesn't show this message.  I don't see the message when I build locally and run from the command line.

```
(coqide.exe:45868): GdkPixbuf-WARNING **: Cannot open pixbuf loader module file 'C:\Coq8.15alpha2\lib\gdk-pixbuf-2.0\2.10.0\loaders.cache': No such file or directory

This likely means that your installation is broken.
Try running the command
  gdk-pixbuf-query-loaders > C:\Coq8.15alpha2\lib\gdk-pixbuf-2.0\2.10.0\loaders.cache
to make things work again for the time being.
```

The command suggested by the message gives the error "The system cannot find the path specified" because there is no `gdk-pixbuf-2.0` directory in `C:\Coq8.15.alpha2\lib`

Originally noted in coq/coq#14800.  See discussion starting [here](https://github.com/coq/coq/issues/14800#issuecomment-916557673).  The issue is thought to be in the Coq repository rather than the platform.

**Comment by Zimmi48** [comment]
Transferred to Coq Platform repository.

**Comment by Zimmi48** [comment]
Another user reported about this issue today on Zulip: https://coq.zulipchat.com/#narrow/stream/237977-Coq-users/topic/Installing.20coqide/near/281121840

**Comment by MSoegtropIMC** [comment]
Since CoqIDE does not need the pixbuf loaders, I just added an empty loader.cache file, which silences the message.
