### ISSUE TITLE
8.15 beta does not work on Windows: cannot open dll

### ISSUE THREAD

**Issue by andrew-appel** [coq/platform#213]
I installed the Coq Platform 8.15 beta pick, with CompCert and VST, using the Windows i686 (32-bit) installer.
coqc fails on any .v file, including (for example) the empty file.

```
$ cat <\dev\null >empty.v
$ coqc empty.v
Dynlink error: error loading shared library: Dynlink.Error (Dynlink.Cannot_open_
dll "Failure(\"Cannot resolve camlAttributes__$2b$2b_268\")")

$ coqc -v
The Coq Proof Assistant, version 8.15.0
compiled with OCaml 4.10.2
```

The Windows 64-bit version (of Coq Platform 8.15 beta pick) fails with a different error message:

```
$ coqc empty.v
Error:
Dynlink error: error loading shared library: Dynlink.Error (Dynlink.Cannot_open_
dll "Failure(\"The operation completed successfully.\\r\\n\")")

```

**Comment by andrew-appel** [comment]
In the Coq Platform 8.14, a similar problem.  For example, in the Windows i686 installer,
```
$ coqc empty.v
Error:
Dynlink error: error loading shared library: Dynlink.Error (Dynlink.Cannot_open_
dll "Failure(\"Cannot resolve camlPcoq__lk_kw_1247\")")

```

**Comment by MSoegtropIMC** [comment]
Weird - I tried both CoqIDE and the (coqc based) smoke test for 32 and 64 bit - but I must admit before signing. I will check again the signed binaries if something went wrong there.

**Comment by andrew-appel** [comment]
Coq_Platform_2021.09.0.8.14+beta2-installer-windows-i686-signed.exe,  same problem.

Coq_Platform_2021.09.0.8.13-installer-windows-i686-signed.exe,  works fine.  This is the same version I have been using for several months, but I verified that re-installing it still works.

**Comment by MSoegtropIMC** [comment]
Would you mind trying an unsigned installer directly from CI - that is e.g. from (https://github.com/coq/platform/actions/runs/1787098461)

**Comment by andrew-appel** [comment]
That works just fine.
https://github.com/coq/platform/suites/5159391104/artifacts/156196869

**Comment by andrew-appel** [comment]
New information:  I think this is related to _where_ I install.  It is not related to signed versus unsigned.  That is, when I install into my usual C:\Coq  directory, where there remains detritus of old installations, I got the problem (with Coq 8.14, Coq 8.15, but not Coq 8.13).  But when I installed in to a different directory, where there also remains detritus (but different, older detritus), then it works fine.  Next I will install into an empty directory, and I expect it will work.

**Comment by andrew-appel** [comment]
Yes, as expected, it works fine.  I am going to close this issue and open a new one about "installing into a nonempty directory causes problems."

**Comment by MSoegtropIMC** [comment]
Thanks for the tests! I created a new issue #214 to add a check in the Windows installer if the destination folder is empty.

Some day we should switch to MSI installers - which handle version migration properly via a system wide installation module database.
