### ISSUE TITLE
Coq Platform 8.14~2022.01 on macOS 10.13.6

### ISSUE THREAD

**Issue by richfh** [coq/platform#220]
Unable to run Coq Platform 8.14~2022.01 on macOS 10.13.6 using the binary installer at:
https://github.com/coq/platform/releases/tag/2022.01.0
which states:
"This installer is only compatible with macOS 10.13 or higher."

However, attempts to run coqtop, coqc tools result in:

dyld: lazy symbol binding failed: Symbol not found: ____chkstk_darwin
Referenced from: 
/Applications/Coq-Platform-8.14~2022.01.app/Contents/Resources/bin/coqtop 
(which was built for Mac OS X 11.0)
Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: ____chkstk_darwin
Referenced from: 
/Applications/Coq-Platform-8.14\~2022.01.app/Contents/Resources/bin/coqtop 
(which was built for Mac OS X 11.0)
Expected in: /usr/lib/libSystem.B.dylib

Attempts to launch CoqIDE result in:

Dyld Error Message:
  Symbol not found: ___kCFBooleanTrue
  Referenced from: 
/Applications/Coq-Platform-8.14\~2022.01.app/Contents/Resources/bin/../lib/dylib/libgdk-3.0.dylib 
(which was built for Mac OS X 11.0)
  Expected in: /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
 in /Applications/Coq-Platform-8.14\~2022.01.app/Contents/Resources/bin/../lib/dylib/libgdk-3.0.dylib

**Comment by Zimmi48** [comment]
Let's also repeat what you said on Zulip:

>Looking around web, other applications have had this problem too, and that Xcode 13.1 will work. It is still available at
https://developer.apple.com/download/all/?q=Xcode%2013

**Comment by richfh** [comment]
I was hesitant to add that to the issue because I haven't verified their claim, but it is worth noting.

**Comment by MSoegtropIMC** [comment]
Current XCode is 13.2.1 (or so) and I doubt that there are changes in supported platforms between 13.1 and 13.2.1. it is likely more a question of command line options and/or the OS version you run it on.

**Comment by MSoegtropIMC** [comment]
I looked around a bit. As far as I can tell the XCode version just sets the default lower limit for the supported OS, but (again afaict) one can override this. The XCode gcc gives the following infos:
```
$ gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 13.0.0 (clang-1300.0.29.30)
Target: x86_64-apple-darwin20.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

$ gcc --help
OVERVIEW: clang LLVM compiler

USAGE: clang [options] file...

OPTIONS:
:
  -mmacosx-version-min=<value>
                          Set Mac OS X deployment target
```
I guess all one has to do is to issue `-mmacosx-version-min=something`. I am not sure I can inject this to opam via environment variables - afaik it does some environment sanitation.

**Comment by MSoegtropIMC** [comment]
See "https://github.com/ocaml/opam/issues/5064".

**Comment by MSoegtropIMC** [comment]
Besides I think one has to inject this into MacPorts / Homebrew as well ...

**Comment by Zimmi48** [comment]
We should have updated the release notes of 2021.01 to acknowledge that the Coq Platform binary installer doesn't work with macOS 10.13, shouldn't we? We know that it works with macOS 10.15, but we have no information regarding macOS 10.14 IIUC.

**Comment by MSoegtropIMC** [comment]
I tested `export MACOSX_DEPLOYMENT_TARGET=10.14` (see https://clang.llvm.org/docs/CommandGuide/clang.html) before running the Coq PlatForm script and this does work:
```
otool -l $(which coqc)
:
Load command 9
      cmd LC_BUILD_VERSION
  cmdsize 32
 platform 1
    minos 10.14
      sdk 12.1
```
@Zimmi48 @richfh : so what should I set? 10.13? I don't think it matters much for Coq and CoqIDE.

Btw.: It will be hard to guarantee that this works for everything, so I would say we recommend 11.0, but try to be compatible to 10.13.

**Comment by richfh** [comment]
> On 29 Sep 2022, at 10:50 AM, MSoegtropIMC ***@***.***> wrote:
> 
> @Zimmi48 <https://github.com/Zimmi48> @richfh <https://github.com/richfh> : so what should I set? 10.13? I don't think it matters much for Coq and CoqIDE.


That would be great for me, assuming it breaks nothing else!

Unclear how many other users there are still on 10.13. 
It is the end of the line update for one of my machines – to be replaced by a new machine running macOS 11.

 — Rich

**Comment by Zimmi48** [comment]
We have some data from the Coq Community Survey from February 2022: https://coq.discourse.group/t/coq-community-survey-2022-results-part-ii/1746
