### ISSUE TITLE
Add Mtac2

### ISSUE THREAD

**Issue by MSoegtropIMC** [coq/platform#24]
Add Mtac2 to the Coq platform.

The maintainers expressed their agreement here:

https://github.com/Mtac2/Mtac2/issues/293#issuecomment-670167496

**Comment by palmskog** [comment]
@MSoegtropIMC if this project is to be added, then you should also open an issue for its dependency, UniCoq, right?

**Comment by MSoegtropIMC** [comment]
Yes, indeed.

**Comment by gares** [comment]
I'm closing this one since mtac2 is now part of the platform.
