### ISSUE TITLE
Extraneous items in loadpath

### ISSUE THREAD

**Issue by jfehrle** [coq/platform#246]
I installed from the Coq platform script. The root of its source tree is `/home/proj/installed-coq-platform/platform`.  I don't see why the items in that directory appear in the loadpath at all.

```
$ which coqide
/home/jfehrle/.opam/__coq-platform.2022.01.0~8.15~beta1/bin/coqide
$ pwd
/home/jfehrle/empty
$ coqide
```

Then `Print LoadPath` shows all these things:

![image](https://user-images.githubusercontent.com/1253341/161706741-6bed3e37-a43c-4e1c-a6e4-ebff7db38dc0.png)

**Comment by MSoegtropIMC** [comment]
This would be much more readable, if you would paste it as text.

I don't have any of this. For me it looks like this:
```
Logical Path / Physical path:
<> /Users/msoegtrop/.opam/__coq-platform.2022.03.0~8.15~2022.03/share/coq
<> /Users/msoegtrop/.opam/__coq-platform.2022.03.0~8.15~2022.03/lib/coq/user-contrib
Mtac2 /Users/msoegtrop/.opam/__coq-platform.2022.03.0~8.15~2022.03/lib/coq/user-contrib/Mtac2
Mtac2.tactics /Users/msoegtrop/.opam/__coq-platform.2022.03.0~8.15~2022.03/lib/coq/user-contrib/Mtac2/tactics
Mtac2.meta /Users/msoegtrop/.opam/__coq-platform.2022.03.0~8.15~2022.03/lib/coq/user-contrib/Mtac2/meta

Many many entries under /Users/msoegtrop/.opam/__coq-platform.2022.03.0~8.15~2022.03/lib/coq/user-contrib

<> /Users/msoegtrop
```

What looks worrying is that you have several space separated paths per Logical path. I can't imagine that Coq Platform contributes in any way to this behavior. It might be something in an environment variable you have or in a _CoqProject file. Otherwise it should be a bug in Coq, not in Coq Platform.

What is your OS?

**Comment by jfehrle** [comment]
I used an image because copying text from X-windows (i.e. Linux processes) to MS windows doesn't work.

Looks like it was COQPATH, thanks.  I've been doing a ton of configuration experiments lately.  Sorry to bother you.

**Comment by MSoegtropIMC** [comment]
> because copying text from X-windows (i.e. Linux processes) to MS windows doesn't work.

yes, that's one of the reasons why I am not a big fan of WSL2.

> Looks like it was COQPATH

thanks for the confirmation - I will close this issue then.

**Comment by jfehrle** [comment]
Windows 11 is supposed to address the cut and paste issue IIUC but I've not gotten around to trying it.
