### ISSUE TITLE
z3_tptp linking problem prevents use in hammer tactic

### ISSUE THREAD

**Issue by palmskog** [coq/platform#248]
After I install the latest `z3` and `z3_tptp` packages via opam on an Ubuntu Linux system, a linking problem prevents the `z3_tptp` executable from working (for example, when using CoqHammer's `hammer` tactic):
```shell
$ z3_tptp
z3_tptp: error while loading shared libraries: libz3.so: cannot open shared object file: No such file or directory
$ ldd `which z3_tptp`
        linux-vdso.so.1 (0x00007fff7a3c6000)
        libz3.so => not found
        libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f0e0cae5000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f0e0caca000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f0e0c8d8000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f0e0c789000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f0e0cd87000)
```
So, do we actually have `libz3.so` installed anywhere? Yes, but not in a location that is part of the LDD path:
```shell
find <opam-switch-path> -name "libz3.so"
<opam-switch-path>/lib/stublibs/libz3.so
$ cat <opam-switch-path>/lib/stublibs/libz3.so.owner 
z3
```
One way to get `z3_tptp` to run is the following, but it's not really a workable long-term solution:
```shell
LD_LIBRARY_PATH=<opam-switch-path>/lib/stublibs z3_tptp
```

**Comment by MSoegtropIMC** [comment]
This is strange in a few ways:

- it works in CI - it is tested there via the smoke test (since 8.15.1 there is a coq-hammer smoke test which actually exercises the ATPs).
- I would think that it is opam's business to ensure that the stublib path is in the load path
- The shared library is not moved after linking, so the binary itself should contain the proper load path

**Comment by palmskog** [comment]
In my environment, the only place I have the `stublibs` path is in the `CAML_LD_LIBRARY_PATH`. However, since `z3_tptp` is a native program and not an OCaml program, I presume it does not read from this variable.

Are you sure the smoke test actually exercises `z3_tptp`? If you have Eprover installed, it will fall back on that, almost silently.

**Comment by MSoegtropIMC** [comment]
The tests are designed to exercise specific provers (see https://github.com/coq/platform/tree/main/test_files/coq-hammer) but I had once the impression that this does not really work - I think I have once seen that it uses z3 when it should have been using eprover.

Can you please check what the load path for the shared library in the executable is?

**Comment by MSoegtropIMC** [comment]
I checked this again and the tests have a work around for this issue (https://github.com/lukaszcz/coqhammer/issues/130) and this work around seems to work, so the smoke test should test the specific provers.

But I must say I am not 100% sure the smoke test is run without Snap - it might be that only snap runs the smoke tests, and this might make linking a bit different.

**Comment by MSoegtropIMC** [comment]
Regarding opam: aren't there opam packages which are wrappers for other shared libraries in the stub lib folder, or is it so that opam expects that all wrappers are for system installed shared libraries?

**Comment by palmskog** [comment]
> Can you please check what the load path for the shared library in the executable is?

I'm not sure what you mean here. After I do `opam install z3 z3_tptp`, I get the following:
- `<opam-switch-root>/bin/z3` (native executable)
- `<opam-switch-root>/bin/z3_tptp` (native executable)
- `<opam-switch-root>/lib/z3` (directory with OCaml wrapper library files for z3)
- `<opam-switch-root>/lib/stublibs/libz3.so` (the native z3 library)

Since the native z3 library (`libz3.so`) is not installed at the system level, it makes sense that it isn't detected by default by the native `z3_tptp` executable, see the [documentation notes](https://github.com/Z3Prover/z3/blob/master/examples/tptp/README#L8-L12).

However, you could in the `z3_tptp` package create a wrapper like the following:
```shell
#!/bin/sh
LD_LIBRARY_PATH=<opam-switch-root>/lib/stublibs z3_tptp.bin "$@"
```
... if you also rename `z3_tptp` to `z3_tptp.bin`. I guess this is what an opam wrapper might do.

**Comment by MSoegtropIMC** [comment]
> I'm not sure what you mean here.

See https://en.wikipedia.org/wiki/Rpath

The wiki page suggest to use `readelf -d <binary_name> | grep 'R.*PATH'` to check it.

Afaik one can give a relative rpath from executable to library, so that this would survive snap packaging, although - again afaik - it would also look under LD_LIBRARY_PATH if it is not under the rpath (this might be OS dependent).

I darkly remember that by default the rpath is wherever the linker found the shared library during link time also on Linux, so this should work. Afair this is what happens on Mac where it does work - on Mac I have to patch the RPATH for the installers to a relative path.

**Comment by palmskog** [comment]
Here is what I get from `readelf` (recall this is a manual opam installation):
```shell
$ readelf -d `which z3_tptp`

Dynamic section at offset 0x56598 contains 30 entries:
  Tag        Type                         Name/Value
 0x0000000000000001 (NEEDED)             Shared library: [libz3.so]
 0x0000000000000001 (NEEDED)             Shared library: [libstdc++.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libgcc_s.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
 0x000000000000000c (INIT)               0x6000
....
```

**Comment by MSoegtropIMC** [comment]
Can you try addind a 

`-Wl,-rpath -Wl,"../lib/stublibs/"`

to the build command for z3_tptp in the opam file (it is a direct call to gcc). This should add a proper RPATH entry to the executable. If this does not work, can you please try with an absolute path?

**Comment by palmskog** [comment]
I used the following diff to the upstream opam file:
```diff
20a21,22
>     "-Wl,-rpath"
>     "-Wl,%{lib}%/stublibs"
```
That is, the new build clause looks as follows:
```
build: [
  [ "g++"
    "-I./src/api/c++"
    "-I./src/api"
    "-std=c++11"
    "-L%{lib}%/stublibs"
    "-o" "z3_tptp"
    "examples/tptp/tptp5.cpp" "examples/tptp/tptp5.lex.cpp" 
    "-lz3"
    "-Wl,-rpath"
    "-Wl,%{lib}%/stublibs"
  ]
]
```
And then it seems to work. For example, I get the following after installing the new local package:
```shell
$ ldd `which z3_tptp`
        linux-vdso.so.1 (0x00007fffb61a5000)
        libz3.so => <opam-switch-root>/lib/stublibs/libz3.so (0x00007f4e84a57000)
        libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f4e84852000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f4e84837000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f4e84645000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f4e84622000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f4e844d3000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f4e863d2000)
```

**Comment by palmskog** [comment]
Also, I tried with `../lib/stublibs/` also, but it didn't work.

**Comment by palmskog** [comment]
If you want to to implement my patch in the upstream `z3_tptp` packages, I think this should be done without changing the package versions (I think this is what you mean by "silently"). Basically, `z3_tptp` as currently packaged in `opam-repository` doesn't work out of the box, and this patch would fix that. The `z3_tptp` package already depends on the `z3` package which installs `libz3.so`, so there seems to be no risk of breaking anything.

**Comment by MSoegtropIMC** [comment]
Except possibly in cases stuff is moved around, but this is not a standard application of opam.

I will change the package then.
