### ISSUE TITLE
Coq Platform 2202.04 Windows installer fails to clear destination directory

### ISSUE THREAD

**Issue by andrew-appel** [coq/platform#254]
I installed the Windows-executable installer for the Coq Platform 2022.04 with Coq 8.15.
In the dialog box for where to install it, I specified C:\Coq88, which is a directory that already existed and was populated with a previous installation of the Coq Platform.

CoqIDE failed to start.

Then it occurred to me to entirely delete the destination directory C:\Coq88 and try the install again.
Now it works fine.

Moral:  Coq Platform installer should delete all contents of the destination directory before installing!

If you want the details of the error, read on; but really the details don't matter so much.

I installed this Windows-executable-installer:
[Coq-Platform-release-2022.04.0-version_8.15_2022.04-windows-i686_signed.exe](https://github.com/coq/platform/releases/download/2022.04.0/Coq-Platform-release-2022.04.0-version_8.15_2022.04-windows-i686_signed.exe)

In the installation dialog box, I chose the install directory,    C:\Coq88

and when I run coqide, I get the following error:
```
Connection with coqtop failed!
Command was ""C:\Coq88\bin\coqidetop.opt.exe" -batch "
Answer was: Error: Dynlink error: error loading shared library: Dynlink.Error (Dynlink.Cannot_open_dll "Failure(\"Cannot resolve camlAttributes__$2b$2b_268\")")

Exception was: Coq.WrongExitStatus("WEXITED 1")
```

**Comment by MSoegtropIMC** [comment]
This is unfortunately not that easy to do with an NSIS installer. As a temporary work around I changed the default name such that it is different for each version.

I plan to switch to MSI installers which uses the Windows installed module database, but it might be quite slow for Coq, since usually one does one module per file because it is not allowed to change which files are in a module.

**Comment by andrew-appel** [comment]
If it's not easy to do with an NSIS installer, then a reasonable alternative would be to use an NSIS installer but put a message in the dialog box saying, "Warning: the target directory should be empty or nonexistent before proceeding", or something like that.

**Comment by MSoegtropIMC** [comment]
It is not even easy to check this in NSIS. In principle NSIS is Turing equivalent, but its language is a bit terse - some sort of stack based assembly language with string registers. To give you an impression, here is a "replace in string" function:

(https://github.com/coq/platform/blob/main/windows/StrRep.nsh)

It is not really that bad, but if I don't do larger changes for a week or so, it takes a lot of overhead for getting into it again.

Btw.: I didn't choose NSIS - it was like this when I took it over around . My preference is WIX (https://wixtoolset.org), but it is a lot of work to change it. Some day I want to switch to WIX with downloadable modules, but this also depends on the code signing infrastructure of INRIA. Currently this is manual and I guess they won't be happy if I throw a few hundred modules for signing at them every release. There are improvements on the way in this area.

**Comment by andrew-appel** [comment]
I was not suggesting that the installer needs to check whether the directory is empty.  It would be helpful if the dialog box could give that warning message even without checking.  Is it difficult to modify the text in the dialog box?

**Comment by MSoegtropIMC** [comment]
I will check that. It is a default dialog box, but one can likely override the text.
