### ISSUE TITLE
Add Unicoq

### ISSUE THREAD

**Issue by MSoegtropIMC** [coq/platform#26]
Since there is a request to add Mtac2, its dependency Unicoq should also be added to the platform.

Technically this is trivial (already done), but we need the agreement of the main authors of Unicoq.

@beta-ziliani, @mattam82: can you please comment here if you agree to adding Unicoq to the Coq platform under the coq platform charter (https://github.com/MSoegtropIMC/coq-platform/blob/master/charter.md) ?

**Comment by beta-ziliani** [comment]
Yes, of course

**Comment by palmskog** [comment]
@MSoegtropIMC currently, Unicoq is restricted to OCaml < 4.08, which would restrict the platform a lot in terms of OCaml versions. See PR #23 by @Zimmi48 for additional discussion on this.

**Comment by mattam82** [comment]
Sure, no problem.

**Comment by MSoegtropIMC** [comment]
@palmskog : Mtac2 and Unicoq have been part of the Windows installer since a while (8.10?) and my plan for the Coq platform 8.11.2 and 8.12.0 is to use OCaml 4.07.1. Do you see substantial issues with the 4.07.1 pick for the Coq platform? I would say must Coq users don't care much, but I understand that developers do care. But then it is easy to edit the Coq platform script for development purposes and switch to a later OCaml and remove Mtac2/Unicoq.

@mattam82, @beta-ziliani : do you see a substantial issue to update Unicoq to support a more recent version of OCaml for the Coq 8.13 release of the platform (in 6 months)?

**Comment by Zimmi48** [comment]
There is a substantial issue (that needs to be solved by Coq developers in fact). Cf. the related discussion on Zulip (https://coq.zulipchat.com/#narrow/stream/250632-Coq-Platform.20devs.20.26.20users/topic/Platform.20OCaml.20versions).

**Comment by gares** [comment]
I'm closing this one since unicoq is now part of the platform.
