### ISSUE TITLE
"Could not read the contents of Desktop" when trying to save my source file on macOS

### ISSUE THREAD

**Issue by ForceBru** [coq/platform#262]
## How to reproduce

1. Open CoqIDE.
2. Go to `File -> Save as`.
3. In the new window, attempt to navigate to `Desktop`.
4. Error will be shown: "Error opening '/Users/whatever/Desktop': Operation not permitted".
5. Same for `Documents` and `Downloads`.

![CoqError](https://user-images.githubusercontent.com/8695383/170771604-0c8a7705-b997-4619-900c-cab3a5ec9cd9.png)

However, CoqIDE never requested permission to access any of these directories, so I can't grant access in Settings.

How do I save my code from CoqIDE?

## Versions

- Coq-Platform-8.15 beta1 and 8.14
- macOS 10.15.7

**Comment by MSoegtropIMC** [comment]
This should already have been fixed in the 2022.04 release from April. Please verify and close.

**Comment by ForceBru** [comment]
@MSoegtropIMC, as far as I understand, the 2022.04 release only supports macOS 11+ (I wonder why that is: 2022.01 runs on 10.13+ - what changed in 2022.04? Is my Mac too old to run a proof assistant?), but I'm stuck on 10.15 because my hardware doesn't support Big Sur and above.

Anyway, I'm unable to run 2022.04, unfortunately, so I guess if this should've been fixed in that version, then it probably was...
