### ISSUE TITLE
Add itauto to the Coq Platform

### ISSUE THREAD

**Issue by palmskog** [coq/platform#265]
[itauto](https://gitlab.inria.fr/fbesson/itauto) is a reflexive intuitionistic SAT solver parameterised by a theory module. When run inside Coq, the theory module wraps an arbitrary Coq tactic, e.g., the `lia` solver for linear arithmetic (`itauto lia`) or the `congruence` solver for uninterpreted function symbols and constructors (`itauto congruence`). The default invocation of `itauto` uses `auto` as a leaf tactic and is then a more stable alternative to `intuition`, which currently does `intuition (auto with *)`. Included is also a more experimental SMT-like tactic `smt` that does Nelson-Oppen combination of `lia` and `congruence`. Key parts of the implementation are described [in a research paper](https://drops.dagstuhl.de/opus/volltexte/2021/13904/pdf/LIPIcs-ITP-2021-9.pdf).

To widen the range of tactics for automation to Coq users, I propose that itauto is included in the Coq Platform. The project has already had regular releases and opam packages since Coq 8.13, most recently for Coq 8.16 (https://github.com/coq/opam-coq-archive/pull/2206) and is part of Coq's CI.

I've already got the go-ahead by email from the author of itauto to propose the Platform inclusion, but pinging him in here as well: @fajb

**Comment by MSoegtropIMC** [comment]
Thanks for the suggestion - the tactic looks very useful indeed. I suggest inclusion in the "full" level.

@fajb: can you please state here that you want itauto included in the Coq Platform in accordance with the Coq Platform [charter](https://github.com/coq/platform/blob/main/charter.md)

**Comment by MSoegtropIMC** [comment]
Thanks - the plan is to add it in the 2022.09 Coq Platform (and its beta releases).

**Comment by palmskog** [comment]
@MSoegtropIMC I'd recommend using two following files as smoke tests, which are part of each release tarball:
- [`test-suite/arith.v`](https://gitlab.inria.fr/fbesson/itauto/-/blob/master/test-suite/arith.v) (tests the core `itauto` tactic)
- [`test-suite/no_test_lia.v`](https://gitlab.inria.fr/fbesson/itauto/-/blob/master/test-suite/no_test_lia.v) (tests the Nelson-Oppen `smt` tactic)

**Comment by MSoegtropIMC** [comment]
@palmskog : with 8.16+rc1 I get an error for arith.v:
```
coqc  arith.v
File "./arith.v", line 3, characters 0-38:
Error: Cannot find a physical path bound to logical path Int63.
```

**Comment by palmskog** [comment]
It looks like `test-suite/arith.v` hasn't been updated for a while (almost one year ago). I'll report the error, but this is only a test file. I suggest using [`refl_bool.v`](https://gitlab.inria.fr/fbesson/itauto/-/blob/master/test-suite/refl_bool.v) for testing instead of `arith.v`.

**Comment by palmskog** [comment]
Ah, it looks like `refl_bool.v` has the same problem. In this case, for this release, I suggest sticking to just `no_test_lia.v` from above, and we'll get it fixed for the next itauto release.
