### ISSUE TITLE
Issue with python_select while installing the Coq Platform (on macOS with MacPorts)

### ISSUE THREAD

**Issue by Casteran** [coq/platform#268]
We have an issue trying to install Coq Platform 2022.04.1 on macOS 12.3.1 with MacPorts. We get the following error message. It seems like the issue is with MacPorts itself, but we thought you ought to know:

```
--->  Installing python_select @0.3_9
Error: Failed to install python_select: no destroot found at: /opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_release_tarballs_ports_sysutils_python_select/python_select/work/destroot
Error: See /opt/local/var/macports/logs/_opt_local_var_macports_sources_rsync.macports.org_release_tarballs_ports_sysutils_python_select/python_select/main.log for details.
Error: Follow https://guide.macports.org/#project.tickets if you believe there
is a bug.
Error: Processing of port adwaita-icon-theme failed
OS package installation failed
```

We get the same issue after running `port selfupdate` and `port upgrade outdated`.

Pierre and Théo (@Zimmi48)

**Comment by MSoegtropIMC** [comment]
This works for me after a port selfupdate and upgrade outdated.

What does `port select --summary` say?

You should try to see what `sudo port install adwaita-icon-theme`. If this fails, you need to debug your MacPorts setup.

**Comment by Casteran** [comment]
Hi, 
  Indeed it looks to be a problem with Macports.
Pierre



>  port select --summary
Name     Selected  Options
====     ========  =======
python   none      base.mp_1642503235 none.mp_1642503235 python25-apple none
python3  none      none

>  sudo port install adwaita-icon-theme

--->  Installing python_select @0.3_9
Error: Failed to install python_select: no destroot found at: /opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_release_tarballs_ports_sysutils_python_select/python_select/work/destroot
Error: See /opt/local/var/macports/logs/_opt_local_var_macports_sources_rsync.macports.org_release_tarballs_ports_sysutils_python_select/python_select/main.log for details.
Error: Follow https://guide.macports.org/#project.tickets if you believe there is
a bug.
Error: Processing of port adwaita-icon-theme failed

**Comment by MSoegtropIMC** [comment]
I see. My (python related) select summary looks like this:
```
FixpointPOC$ port select --summary
Name       Selected       Options
====       ========       =======
pip        pip39          pip3-apple pip39 none
pip2       pip27          none
pip3       pip39          pip3-apple pip39 none
python     python39       python27 python27-apple python310 python36 python38-apple python39 none
python2    python27       python27 python27-apple none
python3    python39       python310 python36 python38-apple python39 none
```
Maybe you can try to get a similar configuration manually (by installing python3.9 and selecting it).

I btw. find it a bit fishy that the adwaita icon theme messes around with python selection, but I guess it does it only temporarily.

Are you on Apple (M1) silicon?

**Comment by Casteran** [comment]
> 
> Are you on Apple (M1) silicon?
> 
> 
No, it’s still an Intel processor

**Comment by MSoegtropIMC** [comment]
@Casteran @Zimmi48 : since a plain `sudo port install adwaita-icon-theme` does not work as reported, I consider this to be an issue in the specific MacPorts installation (I guess the port database is broken). So I will close this issue. If you believe there is anything I can do about this on Coq Platform level, please reopen.
