### ISSUE TITLE
Add CoqEAL to the Coq Platform

### ISSUE THREAD

**Issue by palmskog** [coq/platform#27]
[CoqEAL](https://github.com/CoqEAL/CoqEAL) is (mainly) a library for performing data refinement, such as refining a function using `nat` to a function using binary integers (`Z`) while preserving all relevant properties. Since early 2019, CoqEAL has had releases supporting recent Coq. It depends on the usual MathComp packages already in the platform, as well as Paramcoq and Multinomials.

To my knowledge, there are no similar libraries for performing data refinement in Coq itself (as opposed to in some embedded language). Hence, I propose that CoqEAL is added to the Coq Platform.

The maintainers of CoqEAL are @proux01 and @cohencyril.

**Comment by proux01** [comment]
@MSoegtropIMC it seems that the latest coq-coqeal package now compiles with Coq 8.14+rc1, so this inclusion looks feasible (this would imply including coq-paramcoq #15 and coq-mathcomp-multinomials #25 )

**Comment by MSoegtropIMC** [comment]
Thanks for the note - just in time! I am working today and this weekend on cleaning up my package inclusion backlog. There will btw. also be an updated and extended package pick for Coq 8.13. Coq Platform now supports several package picks (the user is asked during installation which one he wants and one can also install several).

**Comment by MSoegtropIMC** [comment]
Technically this is fine. I picked 'refinements/examples/irred.v' as example for the smoke test kit.

@palmskog, @proux01 : can you please comment if you want to see this in the "full" level (which means you agree to play by the rules of the Coq Platform [charter](https://github.com/coq/platform/blob/2021.02/charter.md)) or in the "extended" level, where rules are more relaxed.

Of course inclusion in the "full" level requires, that the dependencies are also in the full level.

**Comment by proux01** [comment]
If possible wrt dependencies, the "full" level seems appropriate for CoqEAL. It has been reasonnably stable for a few years now and I'll keep making releases compatible with each new Coq version.

**Comment by MSoegtropIMC** [comment]
@proux01 : I included it in the "full" level with (https://github.com/coq/platform/pull/143). One issue though is that it depends on `coq-mathcomp-multinomials` which is still missing an explicit maintainer agreement. If this dependency will be in "extended", CoqEAL has to be in "extended" as well.

**Comment by MSoegtropIMC** [comment]
I postponed the inclusion in the "full" level until the next release, since there was no progress in the maintenance commitment discussion for `coq-mathcomp-multinomials`. CoqEAL will be included in the "extended" level until this is fixed. The next release is planned for November (for 8.14) - it would be good if we could sort this out until then.

Btw.: it would also be possible to include CoqEAL into full while coq-mathcomp-multinomials is in extended if you agree to keep coq-mathcomp-multinomials usable at least for your own purposes.

**Comment by MSoegtropIMC** [comment]
I just got the maintainer agreement for MathComp multinomials, so I will move CoqEAL from "extended" to "full" in 2021.09 8.13 and 8.14+beta.

**Comment by MSoegtropIMC** [comment]
Move from 'extended' to 'full' done in PR (https://github.com/coq/platform/pull/146).

So we are all set and I will close this issue.
