### ISSUE TITLE
Add MathComp Word to the Coq Platform

### ISSUE THREAD

**Issue by palmskog** [coq/platform#271]
[MathComp Word](https://github.com/jasmin-lang/coqword) is a Coq library on machine words based on Mathematical Components. It is a core dependency of [SSProve](https://github.com/SSProve/ssprove) (a [candidate](https://github.com/coq/platform/issues/177) to join the Platform) and other projects such as the [Jasmin compiler](https://github.com/jasmin-lang/jasmin). Machine words are a frequently formalized concept useful in many verification projects.

To allow SSProve and other projects to more easily use MathComp Word, and based on [this discussion on Zulip](https://coq.zulipchat.com/#narrow/stream/237977-Coq-users/topic/Word.20libraries.20and.20duplication/near/289583415), I propose that MathComp Word is added to the Coq Platform.

The primary maintainers of MathComp Word are @vbgl and @strub. In accordance with the [Platform package inclusion process](https://github.com/coq/platform/blob/main/charter.md#package-inclusion-process), we would like for them to comment here that they agree on including the library. In practice, this means committing to making a Git tag for every major Coq release in the GitHub repository (this tag is then ideally packaged in Coq opam repository).

cc: @spitters @gares (can this package use the `coq-math-comp-` prefix?)

**Comment by vbgl** [comment]
I agree that this library be included in the Coq Platform.

**Comment by palmskog** [comment]
@vbgl @strub thanks! I think this means we can get the library into the next Platform release this fall, but @MSoegtropIMC who is currently unavailable, will have to confirm later.

In the meantime, is it OK with you if I package [release 1.1](https://github.com/jasmin-lang/coqword/releases/tag/v1.1) in the Coq opam archive? From what I can tell, it's compatible with 8.16 and MathComp 1.15, so I would adjust bounds accordingly.

**Comment by vbgl** [comment]
> is it OK with you if I package [release 1.1](https://github.com/jasmin-lang/coqword/releases/tag/v1.1) in the Coq opam archive?

It is OK.

**Comment by palmskog** [comment]
`coq-mathcomp-word.1.1` is now out on the archive and marked as compatible with 8.16 and MC 1.15, per https://github.com/coq/opam-coq-archive/pull/2239

For uniformity with other MathComp-related projects, it may be a good idea to change the logpath to something like `mathcomp.word` rather than the current `CoqWord`.

**Comment by MSoegtropIMC** [comment]
@strub : I would appreciate if there would be a Readme.md file in (https://github.com/jasmin-lang/coqword), so that people see what this is good for. There is no need to tag it - it is sufficient if it is available in the main branch.

**Comment by strub** [comment]
Ok. I added a minimal README.

**Comment by MSoegtropIMC** [comment]
Thanks - it is clear and to the point.

**Comment by MSoegtropIMC** [comment]
@strub : there is a new version in opam (https://github.com/coq/opam-coq-archive/pull/2342). Since I am delayed a bit with Coq Platform 2022.09 (but about to release) I wanted to ask if I should update to this version. I need a really quick answer.

**Comment by strub** [comment]
Yes, you can take the last version.

**Comment by MSoegtropIMC** [comment]
@strub : thanks for the quick confirmation. I updated to 2.0.
