### ISSUE TITLE
Add Option for extended Coq Platform to the Installer

### ISSUE THREAD

**Issue by RSoegtrop** [coq/platform#278]
While you can install the extended Coq Platform (including SerAPI) via Scripts, the Installer is missing this option. 
Would it be possible to add a Option like `extended`, with a Flag which marks this as experimental, to the `Choose Components` stage in the Installation Process via Installer?

**Comment by Zimmi48** [comment]
I'm surprised by this request given that the documentation says the following about the extended level:

>The macOS and snap installation bundles always include these packages. The Windows installer also includes them, and they are selected by default.

**Comment by MSoegtropIMC** [comment]
@Zimmi48 : apparently the documentation is wrong - I just verified this. This was introduced during some CI rework (it depends on the Ci setings here https://github.com/coq/platform/blob/eb6727590394a8432a0e8fc47c21b1d2aa075acd/.github/workflows/windows.yml#L28. It is the same for macOS and Linux.

One could make the packages optional (not selected by default) on Windows.

**Comment by RSoegtrop** [comment]
> Are you asking for a way not to install these packages?

Sorry for beeing unclear. I tried to test out SerAPI and there was no way to have it installed by the Installer, simply because the package was not listed in the `Choose Components` list. Even with everything selected, the SerAPI executables where missing. Same with any other Package in the extended Coq Platform. 

Adding an Option like:

> One could make the packages optional (not selected by default) on Windows.

sounds great.

**Comment by MSoegtropIMC** [comment]
For the time being I fixed this by just setting the extent back to x in CI on all platforms. Not sure if it is worthwhile to do something special for Windows now.
