### ISSUE TITLE
Twiddle characters in release name

### ISSUE THREAD

**Issue by buggymcbugfix** [coq/platform#287]
Is it necessary to have `~` characters in the release name? It adds escaping weirdness where my shell (zsh) will print it with backslashes (presumably to stop it from expanding to $HOME, although it shouldn't do that unless it has whitespace on the left anyway). It definitely has caused some confusion for me, amidst an already confusing process of trying to get Coq to install.

**Comment by MSoegtropIMC** [comment]
There were very lengthy discussions and many iterations on the naming and this was the outcome. The naming has to work on many systems and be compatible with version comparison rules of these systems and opam.

So the answer is yes, it has to be like this, unless you come up with a better naming scheme which is compatible with the version comparison rules of all involved operating systems and package managers. Notably replacing the ~ with either -, _, + or . lead to (more severe) issues on at least one involved system.

I am closing this until there is a viable suggestion.

**Comment by buggymcbugfix** [comment]
Would none one of `%`,`,`,`!`,`^` work?

**Comment by MSoegtropIMC** [comment]
% and ^ would for sure create quite a mess on WIndows % is what $ is on Linux and ^ is what \ is on Linux. `,` is not terribly appealing as separator, neither is !. Afair ! also has special meanings in some version comparison schemes.

**Comment by buggymcbugfix** [comment]
Oh no, that's pretty annoying. As you can tell I know nothing about cross-platform development.

Why is `,` not appealing—do you mean visually, or does it conflict in some way? If this is just a visual thing, then imo it's not too bad:

`~/.opam/__coq-platform.2022.04.1,8.15,2022.04/.opam-switch/build/lablgtk3.3.1.2`
vs
`~/.opam/__coq-platform.2022.04.1~8.15~2022.04/.opam-switch/build/lablgtk3.3.1.2`

**Comment by MSoegtropIMC** [comment]
Well maybe. But I am not inclined to change it. I had about 10 iterations on the naming and each one had some severe technical issues on some platform - much more severe then an escaped tilde. This naming scheme is stable since a longer while and there were no real issues. It is also hard to foresee what issues people might have.

**Comment by buggymcbugfix** [comment]
Yeah that makes sense. Thanks for taking the time to go into detail about this nevertheless.
