### ISSUE TITLE
List of supported packages

### ISSUE THREAD

**Issue by spitters** [coq/platform#3]
Is this list available somewhere?

Some suggestions for additions:
* metacoq
* coqprime
* record-update

**Comment by palmskog** [comment]
I would personally like to see added:
- [the Ott tool](https://github.com/ott-lang/ott/) and its support library, the Coq OPAM package `coq-ott`
- coq-dpdgraph
- dune
- CoqHammer
- SerAPI
- Infotheo

**Comment by MSoegtropIMC** [comment]
@palmskog  @spitters : can you please ask the respective package owners to create an issue here (in case you are not yourself). In case you are the owner of one of these packages, please create a separate issue for each package.

**Comment by spitters** [comment]
That would be @mattam82 (metacoq) , @thery (coq-prima), @tchajed (record update)

**Comment by tchajed** [comment]
Opened #6 for record-update.

**Comment by Zimmi48** [comment]
Closing in favor of the individual issues (as suggested by @palmskog).
