### ISSUE TITLE
Elpi: check if the -j 1 opam patch can be removed

### ISSUE THREAD

**Issue by MSoegtropIMC** [coq/platform#314]
See https://github.com/coq/platform/blob/bb768b8431c0fd47a5f10b46cebce0105fd3fe4a/opam/opam-repository/packages/elpi/elpi.1.16.5/opam#L13.

**Comment by gares** [comment]
I was not aware of the problem. What is it?

**Comment by MSoegtropIMC** [comment]
We discussed it a while back - elpi does (or did) not compile reliably in CI without -j 1. It failed in roughly 1 out of 4 runs. With `-j 1` it does run reliably. I took it as action item to check if this was gone by some magic but I couldn't find time to do this (one should do 20 CI runs to be sure) so I left it in. I will remove it after the release, so that we can have proper CI statistics until 8.17.

**Comment by MSoegtropIMC** [comment]
It is not a big deal since elpi also compiles with -j 1 reasonably fast and it is not on the critical path, even with -j 12 or so.

**Comment by gares** [comment]
OK

**Comment by MSoegtropIMC** [comment]
Triage note: latest elpi runs fine in CI with `-j jobs`. As noted above it is not worthwhile to investigate this for older versions since it anyway builds fast (and in parallel with other packages) -> closing.
