### ISSUE TITLE
Error Popup on Windows

### ISSUE THREAD

**Issue by zStruCat** [coq/platform#318]
I installed the current windows msi of 8.15 version released on github. However, open CoqIDE results in the following popup: 
```
(coqide.exe:113024): GdkPixbuf-WARNING **: Cannot open pixbuf loader module file 'C:\Coq-Platform~8.15~2022.04\lib\gdk-pixbuf-2.0\2.10.0\loaders.cache': No such file or directory

This likely means that your installation is broken.
Try running the command
  gdk-pixbuf-query-loaders > C:\Coq-Platform~8.15~2022.04\lib\gdk-pixbuf-2.0\2.10.0\loaders.cache
to make things work again for the time being.
```

I tried gdk-pixbuf... but it doesn't work.
```powershell
PS C:\Users\StarDream>  gdk-pixbuf-query-loaders > C:\Coq-Platform~8.15~2022.04\lib\gdk-pixbuf-2.0\2.10.0\loaders.cache Out-File: Could not find a part of the path 'C:\Coq-Platform~8.15~2022.04\lib\gdk-pixbuf-2.0\2.10.0\loaders.cache'.
```

**Comment by MSoegtropIMC** [comment]
This is just an irrelevant warning - CoqIDE doesn't load TIFFs of JPEGs and doen't need any pixbuf loaders. If it doesn't work, there are other reasons. See the duplicates #212, #270.

I hope you don't get an error popup dialog (as the issue text suggests), just a message in the console. If you indeed get an error dialog, please reopen.
