### ISSUE TITLE
Please include the reduction-effects plugin in the standard install

### ISSUE THREAD

**Issue by JasonGross** [coq/platform#32]
[This plugin](https://github.com/herbelin/reduction-effects) is useful for debugging Gallina, but is extremely hard to discover (it took me three or four searches to find the PR that added support for it (#714 and coq/coq#85)).  I just used it to [answer a discourse thread](https://coq.discourse.group/t/debugging-fixpoint-execution/183/2?u=jasongross).  I think it should be included in the Windows installer, at least.
The first step might be getting the plugin into opam and the CI.

cc @herbelin as the author of the plugin

**Comment by MSoegtropIMC** [comment]
Sorry for the really long delay. I now included it in the 8.13~2021.09 pick and plan to include it in 8.14~2021.09 as well. But since it is a 0.X version, I added it to the extended set - hope this is OK.

I tested the one provided test file and it appears to work.

**Comment by MSoegtropIMC** [comment]
Fixed in https://github.com/coq/platform/pull/143
