### ISSUE TITLE
Add coq-mathcomp-classical to Coq Platform

### ISSUE THREAD

**Issue by proux01** [coq/platform#334]
coq-mathcomp-classical is a subpackage of MathComp Analysis since version 0.6.0. This part has been separated as we consider it can be of interest for users that want classical reasoning with mathcomp without requiring the whole Analysis library. Repo and maintainers remain the same as for Analysis.

Cc: @affeldt-aist (following this Zulip discussion https://coq.zulipchat.com/#narrow/stream/237666-math-comp-analysis/topic/new.20package.20mathcomp-classical )

**Comment by MSoegtropIMC** [comment]
Note that there is an additional request wit maintainer agreement here: https://github.com/coq/platform/issues/339.

**Comment by MSoegtropIMC** [comment]
The 2023.08 picks for Coq 8.16.1 and 8.17.1 include coq-mathcomp-classical.
