### ISSUE TITLE
coq-mathcomp-classic as part of the package pick?

### ISSUE THREAD

**Issue by affeldt-aist** [coq/platform#339]
coq-mathcomp-classical is currently installed with the Coq platform as a dependency of coq-mathcomp-analysis.

It is however not listed as part of the package pick although it can be useful on it own, for example to perform set theoretic reasoning.

It might be worth considering listing coq-mathcomp-classical along with coq-mathcomp-analysis as part of the package pick.

**Comment by MSoegtropIMC** [comment]
Actually I just saw that there was already a request to include coq-mathcomp-classic here : https://github.com/coq/platform/issues/334

So I will close this issue (but note it as additional maintainer agreement).
