### ISSUE TITLE
Documentation has references to github.com/MSoegtropIMC

### ISSUE THREAD

**Issue by andrew-appel** [coq/platform#35]
Now that the official home of the Coq Platform is github.com/coq/platform, there are references to github.com/MSoegtropIMC/coq-platform that should be changed.
These are in the `README.md`, but also in the release notes for the beta1 tag, that is, `https://github.com/coq/platform/blob/v8.12.0+beta1/README.md`

**Comment by Zimmi48** [comment]
I've just fixed these references in the `master`, `v8.12` and `v8.13` branches (both in the README and in shell scripts) + in the 8.12 beta1 release. The only occurrences that remain are those in the opam patches (I considered these are unimportant).
