### ISSUE TITLE
How to make the documentation more user-friendly

### ISSUE THREAD

**Issue by andrew-appel** [coq/platform#36]
README.md is addressed to coq developers and other sophisticated insiders.  This was appropriate when this Platform was under initial development, but now we should hope that most readers of the documentation will be ordinary users.  Therefore, I would suggest:

1.  Most users should not clone the repo, but just download a release.

2. Split README.md into two files, the other being USAGE.md, which explains how to use the Coq Platform.  All the material starting with "Usage of the ..." should be in USAGE.md.  In the README, right before Note on Licenses, there should be:
    * Suggestion to choose the latest release from github.com/coq/platform/releases
    * Prominent link to USAGE.md.

3.  The release notes (the "body" text of the release) should have a prominent link to USAGE.md

4. Proposed edits of USAGE.md are attached
[USAGE.txt](https://github.com/coq/platform/files/5282917/USAGE.txt)
(My apologies for doing it this way, instead of more professionally as a pull request.)

5.  It is "brittle" to have the switch-name repeated so many times in USAGE.md.  It would be better to generate USAGE.md from a script that pastes in the result of calculating the name via coq_platform_switch_name.sh.

**Comment by dnaumann** [comment]
Suggested addition to the documentation: how to maintain the installation.
In particular, is it sufficient to run opam upgrade once coq-platform is installed successfully.

**Comment by MSoegtropIMC** [comment]
Sorry for the long delay! The README changed a lot since then and most of the comments are already implemented - notably the file is split into several pieces in the main branch since a while. I took the zip vs git comment into account in PR #160.

The comment from @dnaumann lead to a new expandable section in the main readme file, also in PR #160.
