### ISSUE TITLE
changed code signature in macOS release 8.17.1~2023.08?

### ISSUE THREAD

**Issue by suschizu** [coq/platform#364]
hello @MSoegtropIMC - I've noticed the the code signature has changed in the macOS version:

`EXPECTED 'Fondation Inria (9T7GED4ND7)' but FOUND 'INRIA (G7J8NYU3HT)'`

can you confirm the update? Thanks!

**Comment by MSoegtropIMC** [comment]
I can confirm that the previous signing key expired and the installers are signed by a different INRIA centralised process. So this is plausible, but I can't confirm the fingerprint, since I am no longer involved in the signing process.

**Comment by suschizu** [comment]
thanks for the fast answer!
