### ISSUE TITLE
Cygwin installation: The system cannot find the path specified.

### ISSUE THREAD

**Issue by yforster** [coq/platform#38]
We're using the Coq platform in a lecture to let students install Coq with packages on Windows.

A student is experiencing the following error:

```
"========== DOWNLOAD CYGWIN SETUP =========="
Exception calling "DownloadFile" with "2" argument(s): "An exception occurred during a WebClient request."
At line:1 char:1
+ (New-Object Net.WebClient).DownloadFile('http://www.cygwin.com/setup- ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : WebException

"========== INSTALL CYGWIN =========="
The system cannot find the path specified.
ERROR coq_platform_make_windows.bat failed
```

Any hints?

**Comment by MSoegtropIMC** [comment]
@yforster : sorry for the long delay in answering this (I am more responsive on Zulip, but guess I need to improve on this ...).

This is simply a network error - the script could not download the cygwin setup program from the official download site.
