### ISSUE TITLE
Snap release 8.18 / 2023.11.0

### ISSUE THREAD

**Issue by niluxv** [coq/platform#397]
Would it be possible to release Coq Platform 2023.11.0 with Coq 8.18 on [snapcraft](https://snapcraft.io/coq-prover)? It currently serves Coq Platform 2023.08 with Coq 8.17.1 (even on the `latest/edge` channel).

**Comment by MSoegtropIMC** [comment]
The release notes say clearly that this is being worked on. We don't have the process fully in our hands. We first have to request a new track on the snap stores. See https://forum.snapcraft.io/t/2023-11-track-creation-for-coq-prover/38721. Usually this takes a few days. If the track has been created, the snap will be uploaded. Before it is technically not possible to do it.

Maybe it helps if you upvote the track creation request. For the time being I can't do anything, so I will close this issue.
