### ISSUE TITLE
missed dependency checks? (autoconf and automake)

### ISSUE THREAD

**Issue by dnaumann** [coq/platform#40]
As I understand the script is meant to detect and resolve all dependencies.  On macOS I pulled the current version of beta1 (commit 1dfaf7c622943ac5d44aefcd00d9a50) and ran it to install including full CompCert and VST.  It prompted me to run port to install some dependencies (bison boost flex gmp mpfr) but then broke because autoconf was missing.  After I installed autoconf, it got as far as VST but failed on gappa which requires aclocal (transcript attached). After using port to install automake, the coq-platform installation completed successfully.   

[coq-platform-error-aclocal.txt](https://github.com/coq/platform/files/5586922/coq-platform-error-aclocal.txt)

**Comment by MSoegtropIMC** [comment]
Thanks for reporting and sorry for the long delay ...

This appears to be a dependency issues with one of the involved opam packages - I will try to install each of them with an empty MacPorts and see what happens.

**Comment by MSoegtropIMC** [comment]
Triage note: we regularly build on fresh MacPorts and Homebrew and this works, so I expect that this is fixed meanwhile.
