### ISSUE TITLE
README incorrectly says there's no binary release for Apple Silicon

### ISSUE THREAD

**Issue by tchajed** [coq/platform#404]
The README says to use the "from sources" method for "Apple Silicon / M1". This is out of date; there's now a binary dmg release for arm64.

Also note that referring to "M1" is now confusing since there are M2 and M3 processors. arm64 would be a better keyword to mention.

**Comment by MSoegtropIMC** [comment]
Thanks for the report - this is indeed both wrong.

**Comment by tchajed** [comment]
Just FYI that this still isn't fixed. I believe you should consider macOS to approximately mean Apple Silicon at this point. I ran into these instructions seeing them linked from the setup instructions for [this class at MPRI](https://mpri-prfa.github.io/installcoq.html).

**Comment by pauloud** [comment]
Hello, I am curious about a point : I have an apple sillicon, but if I had an Intel one, which method should I pick ?

**Comment by rtetley** [comment]
> Hello, I am curious about a point : I have an apple sillicon, but if I had an Intel one, which method should I pick ?

At this stage, I believe it's no longer about which type of processor you have but rather how experienced you are
