### ISSUE TITLE
Warning on non-existing opam repo

### ISSUE THREAD

**Issue by fakusb** [coq/platform#41]
On my machine (wsl with archlinux), I get a warning:
````
Found opam 2.0.7 - good!   /usr/sbin/opam 
===== opam already initialized =====
===== CREATE OPAM SWITCH =====
[WARNING] No configured repositories by these names found: patch_coq-platform_.8.12.0+beta1                                                    [patch_coq-platform_.8.12.0+beta1] Initialised    
````

**Comment by MSoegtropIMC** [comment]
Sorry for the long response time.

I don't have a good explanation for this issue. Can you still remember if this happened with a release version of Coq Platform or with a master branch version? I did a lot of renaming around this time. The patch repo names now look more like `__coq-platform.2021.09.0.patch_ocaml `.

**Comment by fakusb** [comment]
I think it was `tags/v8.12.0+beta1`, and I think I did not install it before. But opam was already installed on the machine.l

**Comment by MSoegtropIMC** [comment]
The `tags/v8.12.0+beta1` had a rather old script state. I would think that with the new multi-version support these issues are gone. One can now install Coq 8.12 with the latest version of the scripts, so that the old script versions for older Coq versions need not be maintained any longer.
