### ISSUE TITLE
Please avoid Dune 3.13-3.15

### ISSUE THREAD

**Issue by Alizter** [coq/platform#410]
Hi,

Unfortunately the releases of Dune 3.13.1, 3.14.2 and 3.15.1 all contain a serious bug where any changes in the output of coqdep will cause Dune to rebuild all `.v` files. This doesn't affect the main Coq build only projects that use Dune to build, such as HoTT/Coq-HoTT. The main build in the platform will be fine, but users with Dune projects based on the platform will be annoyed by the constant rebuilds.

I therefore recommend avoiding those versions. I've already submitted a fix for this issue upstream:

- https://github.com/ocaml/dune/pull/10446

and most likely that will appear in a point release for 3.15. Probably 3.15.2. However this still means that previous versions 3.13 and 3.14 will have this bug. I will speak with the Dune team to ask for those to be back ported also.

Regarding the platform, I'm not exactly sure which Dune version you have chosen, but I wanted to give you a heads up that this issue was present. If by the time you cut a new release we have 3.15.2 then I would recommend using that for the platform, if not then I would recommend sticking with 3.12 if it is possible with the package constraints.

**Comment by MSoegtropIMC** [comment]
Triage note: we are currently only using dune 3.15.3 and 3.4.1, so closing.
