### ISSUE TITLE
Editor context painting for Axiom wrong

### ISSUE THREAD

**Issue by Iainmon** [coq/platform#441]
<img width="843" alt="screenshot" src="https://github.com/user-attachments/assets/2163e966-4f9c-4728-ad0f-ed571718e35f">

Notice line 46. Paints anything I type (even comments) as yellow beyond col 5. 

<img width="837" alt="screenshot" src="https://github.com/user-attachments/assets/626a979c-2918-45f0-bf07-0790419d45d8">

**Comment by Zimmi48** [comment]
Issues regarding VsCoq-legacy should be reported in their own issue tracker: https://github.com/coq-community/vscoq-legacy/issues

(I guessed this is VsCoq-legacy, but the report does not provide enough details to know for sure.)
