### ISSUE TITLE
Extrude artifact filtering code from windows installer

### ISSUE THREAD

**Issue by gares** [coq/platform#47]
The snap package needs to trim down the opam root as well.
The filtering code is a bit tied to nsh files, some refactoring may be needed in order to reuse it.
Something like `for f in $files; do cp $f $SNAP_PART_INSTALL/; done` is sufficient, but today $files is "implicit" in the .nsh files which are almost lists of files but not entirely

**Comment by MSoegtropIMC** [comment]
@gares : I must admit I don't understand the description of this issue. Do you plan to do this? Is it easy? Can you point me to the code?

**Comment by gares** [comment]
The code for windows selects files from an opam switch to be copied in the installer.
The code for snap removes files which are not needed in order to run coq from the opam switch.

The list of files to keep/remove is the same, and is computed correctly only on windows (the snap script does not even try).

**Comment by MSoegtropIMC** [comment]
I completely reworked the snap file selection - it is now a positive filtering based of `opam show --list-files` and identical with MacOS and Windows.
