### ISSUE TITLE
Add record-update

### ISSUE THREAD

**Issue by tchajed** [coq/platform#6]
I'd like to add https://github.com/tchajed/coq-record-update to the Coq platform.

**Comment by MSoegtropIMC** [comment]
@tchajed : thanks for the request! I saw that the project is version 0.2.0. Do you expect substantial changes? if not, why is it a 0.X release?

One of the goals of the coq platform is to provide an environment which is as stable as possible. So including beta software requires some extra justification and/or additional handling like marking it clearly as beta.

**Comment by tchajed** [comment]
I don't really expect changes, it's been stable for a long time now other than bug fixes. I used v0.2.0 because committing to the API seemed scary, but if that's helpful for the platform I can just declare it to be version v1.0.0.

**Comment by Zimmi48** [comment]
Yes, if the API has turned out to be stable for some time already, it should be time to commit to it by making an 1.0.0 release to get into the platform. Note that the first release of the platform will be experimental, so somehow more relaxed, but eventually, this kind of considerations will become stricter constraints.

**Comment by MSoegtropIMC** [comment]
I agree with @Zimmi48 : if it is stable this should be made explicit by naming it 1.0.

**Comment by MSoegtropIMC** [comment]
Sorry for the long delay! I now added coq-record-update to the updated 2021.09 pick for Coq 8.13 and plan to add it to Coq 8.14 as well.

Since it still has a 0.X version number, I added it to the "extended" level (Coq Platform has a basic, full and extended level).

**Comment by Zimmi48** [comment]
@tchajed Please do a 1.0 release so that it can be included in the full level.
