### ISSUE TITLE
[wish] [snap] source pre downloading

### ISSUE THREAD

**Issue by gares** [coq/platform#63]
This wish would enable snapcraft.io to build for us the snap package on architecture other than x86_64 (eg aarch64). I don't know how popular linux PC on arm will become in the near future, so it's not super high priority. Today we are limited to x86_64 since the github action runners are only on this arch (one can add a custom linux runner if he wants, but we don't have one).

The problem is that snapcraft remote build happens in a sadboxed environment which has no network access: all the sources need to be downloaded as a build dependency or as a source entry in the snap file.

The request is:
- a mode where the scripts only download the sources (of opam files, but also opam installer), to be run locally before calling `snapcraft remote-build --build-on=arm64`
- a mode were a local directory is used to "download" sources of things (both by the scripts and by opam), to be used by the scripts when run from the snap

I have no idea how feasilble this is. Maybe it's easier to buy an arm linux box and link it to github actions.

**Comment by gares** [comment]
apparently opam 1.2 will have:
> opam install now has a --download-only flag, allowing opam's caches to be primed

**Comment by MSoegtropIMC** [comment]
@gares : do you want to put yourself in as assignee for this?

**Comment by gares** [comment]
I don't have time to implement it anytime soon :-/

**Comment by MSoegtropIMC** [comment]
Triage note: we already have difficulties to maintain the platforms we already have, so I am very reluctant to add new platforms without justification.

Another reason is that CI burns quite a bit of electricity for each platform we add.
