### ISSUE TITLE
Compilation experience report

### ISSUE THREAD

**Issue by LasseBlaauwbroek** [coq/platform#66]
I did an installation of the platform on a fresh Windows 10 install that came stock with a notebook. Most things went fine, but I did have a few issues (some of them are just things that might be useful to document in the readme):

- I had to set `git config --global core.autocrlf false` before cloning the git repo. Otherwise, the bash scripts won't execute, because they contain carriage returns
- I had to disable some scanners. In particular 'HP Sure Sense' (whatever that is) and 'Windows real-time protection'
- I had to change this line https://github.com/coq/platform/blob/4c142687b5c5fbe29f7db185e3a497a4b42ff0d9/shell_scripts/install_opam.sh#L50 to `bash opam64/install.sh --prefix /usr/sys-root/mingw`

Otherwise, everything was pretty smooth! Much better than the previous installer for windows.

**Comment by Zimmi48** [comment]
What do you mean by this?

> Much better than the previous installer for windows.

**Comment by LasseBlaauwbroek** [comment]
I mean that customizing coq platform is much easier than the way one could generate a windows custom installer previously (using the code that is in the main Coq repo). And  by customizing I mean adding/removing packages.

**Comment by MSoegtropIMC** [comment]
@LasseBlaauwbroek : can you give some more details on the Virus scanner settings you used? E.g. a screen shot of the default and after settings would be nice. Also example error messages when the scanners are enabled would be helpful.

I will add notes about the git config settings (what you have should be the default for Cygwin git, but not for "GIT for Windows".

**Comment by LasseBlaauwbroek** [comment]
Attached are some images. The virues scanners seem to be unhappy about the downloading of the opam binary. To turn of HP Sure Sense, go to the HP Sure Sense App -> Settings -> Advanced Settings -> Edit and turn of Threat Protection.

![sure-sense-after](https://user-images.githubusercontent.com/1413089/107117315-e6f3c900-6879-11eb-81b0-beacd7b2ef99.PNG)
![sure-sense-before](https://user-images.githubusercontent.com/1413089/107117316-e824f600-6879-11eb-9539-dff8d63b9701.PNG)
![virus-messages](https://user-images.githubusercontent.com/1413089/107117320-ea875000-6879-11eb-89bf-1bf2d75740cf.png)
![virus-threat-after](https://user-images.githubusercontent.com/1413089/107117322-ece9aa00-6879-11eb-8feb-a4d349a836c3.PNG)
![virus-threat-before](https://user-images.githubusercontent.com/1413089/107117325-ef4c0400-6879-11eb-9c0d-5abb04495e69.PNG)

**Comment by LasseBlaauwbroek** [comment]
Note that I just turned everything I could find off, because I don't really care about the security of this machine. There may be more subtle methods.

**Comment by MSoegtropIMC** [comment]
Thanks! Since it seems to be about a specific file it might also make sense to report a false positive. With GData I have more the issue that it crawls folders which in windows has the effect that deleting the folder is denied - so the effects I see are random failures on a rm or mv.

**Comment by LasseBlaauwbroek** [comment]
Ah, I never use scanners normally, so I have no idea how such reporting would work...

**Comment by MSoegtropIMC** [comment]
I took the feedback comments into account in PR #160. Thanks!
