### ISSUE TITLE
HoTT

### ISSUE THREAD

**Issue by spitters** [coq/platform#7]
Add [HoTT](https://github.com/HoTT/HoTT)

**Comment by Zimmi48** [comment]
How stable is HoTT nowadays? It's hard to tell from the version numbering scheme since it just mimics the one of Coq.

Another question is the non-standard `hoqtop` / `hoqc` / `hoqide` commands that it introduces. Isn't it time to get rid of those? Maybe getting in the platform would be a good trigger for doing this.

**Comment by spitters** [comment]
@alizter just mentioned that he got HoTT to compile with the stdlib. Together with @ejgallego.
So, this should greatly simplify the inclusion in platform.
This is quite exciting!

**Comment by Alizter** [comment]
@spitters I got HoTT to compile *without* the stdlib using the noinit argument.

**Comment by Alizter** [comment]
Once I can get the noinit stuff merged into the main branch, we can think about getting rid of the current makefile setup. There are still some decisions about the html docs, dependency graphs etc. that need to be sorted out. That will let us to eventually get rid of the hoq commands.

**Comment by palmskog** [comment]
@Alizter @spitters when do we get a package in the Coq opam archive for HoTT for 8.12? Is this planned at all?

**Comment by k4rtik** [comment]
It seems HoTT is already included in the latest platform release #97 and #99 by @MSoegtropIMC, however, it doesn't seem locatable:

```
$ rlwrap coqtop
Welcome to Coq 8.13.2 (April 2021)

Coq < Require Import Coq.HoTT.
Toplevel input, characters 15-23:
> Require Import Coq.HoTT.
>                ^^^^^^^^
Error: Unable to locate library Coq.HoTT. (While searching for a .vos file.)
```

I can't find binaries like `hoqtop` or `hoqc` either. Is all this expected?

**Comment by Alizter** [comment]
@k4rtik Yes it is expected not to find the `hoq` scripts. The HoTT library should work with regular `coq_makefile`, `coqide` etc

**Comment by k4rtik** [comment]
```
```

**Comment by Alizter** [comment]
Try
```
From HoTT Require Import HoTT.
```

**Comment by k4rtik** [comment]
Got it, that works.

Thanks. Perhaps this issue can now be closed?
