### ISSUE TITLE
A README with `<details><summary>` for the Coq Platform?

### ISSUE THREAD

**Issue by Zimmi48** [coq/platform#96]
@erikmd just showed me this README: https://github.com/erikmd/tapfa-init.el
It's a detailed guide in French on how to install Coq on different platform.
A key presentation aspect is the use of `<details>` and `<summary>` to hide most of the details by default.
I'm thinking this might be useful for the platform as well: instead of many READMEs, all pretty long, provide a single one, with folded sections.
WDYT?

**Comment by MSoegtropIMC** [comment]
I picked up this idea in the README file(s) of the main branch - I like it.
